/** <pre>
 *  Copyright 2004 The Boeing Company
 *
 *  This program is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation; either version 2.1 of the License, or (at
 *  your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 *  details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this software; if not, write to the Free Software Foundation,
 *  Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 *  FILENAME:   HemuMsg.cpp
 *  LANGUAGE:   C++
 *  CLASS:      UNCLASSIFIED
 *  PROJECT:    Common Image Generator Interface Host Emulator (CIGI HE)
 *
 *  PROGRAM DESCRIPTION:
 *  The Host Emulator (HE) acts as a surrogate in the absence of a simulation host.
 *
 *  MODIFICATION NOTES:
 *  DATE     NAME
 *  DESCRIPTION OF CHANGE
 *
 *  11/11/2004 Lance Durham
 *  Initial Release.
 * </pre>
 *  The Boeing Company
 *  Version 3.1.1
 */

#include "hemumsg.h"
#include "string.h"

// Base class default constructor.
HEMU_MESSAGE::HEMU_MESSAGE()
    : msg(MSG_GENERIC), size(sizeof(HEMU_MESSAGE))
{
}

// Base class initialization constructor -- used to initialize const
// members in subclass' constructors.
HEMU_MESSAGE::HEMU_MESSAGE(unsigned long type, unsigned long sz)
    : msg(type), size(sz)
{
}

// Base class operator=.
HEMU_MESSAGE &HEMU_MESSAGE::operator=(const HEMU_MESSAGE &src)
{
    memcpy(this, &src, size);
    return *this;
}

MESSAGE_ADD_ENTITY::MESSAGE_ADD_ENTITY()
    : HEMU_MESSAGE(MSG_ADD_ENTITY, sizeof(MESSAGE_ADD_ENTITY))
{
}

MESSAGE_DEL_ENTITY::MESSAGE_DEL_ENTITY()
    : HEMU_MESSAGE(MSG_DEL_ENTITY, sizeof(MESSAGE_DEL_ENTITY))
{
}

MESSAGE_CLEAR_ENTITIES::MESSAGE_CLEAR_ENTITIES()
    : HEMU_MESSAGE(MSG_CLEAR_ENTITIES, sizeof(MESSAGE_CLEAR_ENTITIES))
{
}

MESSAGE_ADD_VIEW::MESSAGE_ADD_VIEW()
    : HEMU_MESSAGE(MSG_ADD_VIEW, sizeof(MESSAGE_ADD_VIEW))
{
}

MESSAGE_DEL_VIEW::MESSAGE_DEL_VIEW()
    : HEMU_MESSAGE(MSG_DEL_VIEW, sizeof(MESSAGE_DEL_VIEW))
{
}

MESSAGE_CLEAR_VIEWS::MESSAGE_CLEAR_VIEWS()
    : HEMU_MESSAGE(MSG_CLEAR_VIEWS, sizeof(MESSAGE_CLEAR_VIEWS))
{
}

MESSAGE_ADD_VIEWGROUP::MESSAGE_ADD_VIEWGROUP()
    : HEMU_MESSAGE(MSG_ADD_VIEWGROUP, sizeof(MESSAGE_ADD_VIEWGROUP))
{
}

MESSAGE_DEL_VIEWGROUP::MESSAGE_DEL_VIEWGROUP()
    : HEMU_MESSAGE(MSG_DEL_VIEWGROUP, sizeof(MESSAGE_DEL_VIEWGROUP))
{
}

MESSAGE_CLEAR_VIEWGROUPS::MESSAGE_CLEAR_VIEWGROUPS()
    : HEMU_MESSAGE(MSG_CLEAR_VIEWGROUPS, sizeof(MESSAGE_CLEAR_VIEWGROUPS))
{
}

MESSAGE_PAUSE_EXERCISE::MESSAGE_PAUSE_EXERCISE()
    : HEMU_MESSAGE(MSG_PAUSE_EXERCISE, sizeof(MESSAGE_PAUSE_EXERCISE))
{
}

MESSAGE_RUN_EXERCISE::MESSAGE_RUN_EXERCISE()
    : HEMU_MESSAGE(MSG_RUN_EXERCISE, sizeof(MESSAGE_RUN_EXERCISE))
{
}

MESSAGE_RESET_HOST::MESSAGE_RESET_HOST()
    : HEMU_MESSAGE(MSG_RESET_HOST, sizeof(MESSAGE_RESET_HOST))
{
}

MESSAGE_RESET_IG::MESSAGE_RESET_IG()
    : HEMU_MESSAGE(MSG_RESET_IG, sizeof(MESSAGE_RESET_IG))
{
}

MESSAGE_SET_ADDR::MESSAGE_SET_ADDR()
    : HEMU_MESSAGE(MSG_SET_ADDR, sizeof(MESSAGE_SET_ADDR))
{
    ip_addr[0] = '\0';
    hud_ip_addr[0] = '\0';
    send_port = 0;
    rcv_port = 0;
    hud_send_port = 0;
}

MESSAGE_SHUTDOWN::MESSAGE_SHUTDOWN()
    : HEMU_MESSAGE(MSG_SHUTDOWN, sizeof(MESSAGE_SHUTDOWN))
{
}

MESSAGE_ADD_HAT::MESSAGE_ADD_HAT()
    : HEMU_MESSAGE(MSG_ADD_HAT, sizeof(MESSAGE_ADD_HAT))
{
    id_base = 0;
    entity_id = -1;
    request_type = 0;
    coord_system = 0;
    continuous = 0;
    reserved1 = 0;
    reserved2 = 0;
    lat = 0.0;
    lon = 0.0;
    alt = 0.0;
    x_offset = 0.0;
    y_offset = 0.0;
    z_offset = 0.0;
}

MESSAGE_ADD_LOS::MESSAGE_ADD_LOS()
    : HEMU_MESSAGE(MSG_ADD_LOS, sizeof(MESSAGE_ADD_LOS))
{
    id_base = 0;
    req_type = 0;
    ext_response = 0;
    src_coord_system = 0;
    dest_coord_system = 0;
    resp_coord_system = 0;
    continuous = 0;
    use_target_entity = 0;
    alpha_thresh = 0;
    target_entity_id = 0;
    material_mask = 0;
    entity_id = -1;
    target_entity_id = 0;
    azimuth = 0.0;
    elevation = 0.0;
    min_range = 0.0;
    max_range = 0.0;
    src_lat = 0.0;
    src_lon = 0.0;
    src_alt = 0.0;
    src_x_offset = 0.0;
    src_y_offset = 0.0;
    src_z_offset = 0.0;
    dest_lat_x = 0.0;
    dest_lon_y = 0.0;
    dest_alt_z = 0.0;


}

MESSAGE_BEGIN_RECORD::MESSAGE_BEGIN_RECORD()
    : HEMU_MESSAGE(MSG_BEGIN_RECORD, sizeof(MESSAGE_BEGIN_RECORD))
{
    memset(filename, '\0', sizeof(filename));
}

MESSAGE_END_RECORD::MESSAGE_END_RECORD()
    : HEMU_MESSAGE(MSG_END_RECORD, sizeof(MESSAGE_END_RECORD))
{
}

MESSAGE_BEGIN_PLAYBACK::MESSAGE_BEGIN_PLAYBACK()
    : HEMU_MESSAGE(MSG_BEGIN_PLAYBACK, sizeof(MESSAGE_BEGIN_PLAYBACK))
{
    memset(filename, '\0', sizeof(filename));
}

MESSAGE_END_PLAYBACK::MESSAGE_END_PLAYBACK()
    : HEMU_MESSAGE(MSG_END_PLAYBACK, sizeof(MESSAGE_END_PLAYBACK))
{
}

MESSAGE_PAUSE_RECPLAYBACK::MESSAGE_PAUSE_RECPLAYBACK()
    : HEMU_MESSAGE(MSG_PAUSE_RECPLAYBACK, sizeof(MESSAGE_PAUSE_RECPLAYBACK))
{
}

MESSAGE_RESUME_RECPLAYBACK::MESSAGE_RESUME_RECPLAYBACK()
    : HEMU_MESSAGE(MSG_RESUME_RECPLAYBACK, sizeof(MESSAGE_RESUME_RECPLAYBACK))
{
}

MESSAGE_SET_DATABASE::MESSAGE_SET_DATABASE()
    : HEMU_MESSAGE(MSG_SET_DATABASE, sizeof(MESSAGE_SET_DATABASE))
{
    dbnum = 0;
    lat = 0;
    lon = 0;
    radius = 6378137.0;
    flattening = 1 / 298.257223563;
}

MESSAGE_SET_TRACKER_STATE::MESSAGE_SET_TRACKER_STATE()
    : HEMU_MESSAGE(MSG_SET_TRACKER_STATE, sizeof(MESSAGE_SET_TRACKER_STATE))
{
    enable = 0;
}

MESSAGE_SET_TRACKER_BORESIGHT::MESSAGE_SET_TRACKER_BORESIGHT()
    : HEMU_MESSAGE(MSG_SET_TRACKER_BORESIGHT, sizeof(MESSAGE_SET_TRACKER_BORESIGHT))
{
    boresight = 0;
}

MESSAGE_SET_IG_MODE::MESSAGE_SET_IG_MODE()
    : HEMU_MESSAGE(MSG_SET_IG_MODE, sizeof(MESSAGE_SET_IG_MODE))
{
    mode = 0;
}

MESSAGE_SET_IG_CONTROL::MESSAGE_SET_IG_CONTROL()
    : HEMU_MESSAGE(MSG_SET_IG_CONTROL, sizeof(MESSAGE_SET_IG_CONTROL))
{
    smoothing_enabled = true;
    substitution_enabled = true;
}

MESSAGE_SET_HUD_STATE::MESSAGE_SET_HUD_STATE()
    : HEMU_MESSAGE(MSG_SET_HUD_STATE, sizeof(MESSAGE_SET_HUD_STATE))
{
    state = 0;
}

MESSAGE_REMOVE_HAT::MESSAGE_REMOVE_HAT()
    : HEMU_MESSAGE(MSG_REMOVE_HAT, sizeof(MESSAGE_REMOVE_HAT))
{
    id_base = 0;
}

MESSAGE_REMOVE_LOS::MESSAGE_REMOVE_LOS()
    : HEMU_MESSAGE(MSG_REMOVE_LOS, sizeof(MESSAGE_REMOVE_LOS))
{
    id_base = 0;
}

MESSAGE_PLAYBACK_EOF::MESSAGE_PLAYBACK_EOF()
    : HEMU_MESSAGE(MSG_PLAYBACK_EOF, sizeof(MESSAGE_PLAYBACK_EOF))
{
}

MESSAGE_FILE_ERROR::MESSAGE_FILE_ERROR()
    : HEMU_MESSAGE(MSG_FILE_ERROR, sizeof(MESSAGE_FILE_ERROR))
{
    memset(filename, '\0', sizeof(filename));
}

MESSAGE_FRAME_RATE::MESSAGE_FRAME_RATE()
    : HEMU_MESSAGE(MSG_FRAME_RATE, sizeof(MESSAGE_FRAME_RATE))
{
    framerate = 0;
}

MESSAGE_NO_CONNECT::MESSAGE_NO_CONNECT()
    : HEMU_MESSAGE(MSG_NO_CONNECT, sizeof(MESSAGE_NO_CONNECT))
{
}

MESSAGE_MISSILE_HIT::MESSAGE_MISSILE_HIT()
    : HEMU_MESSAGE(MSG_MISSILE_HIT, sizeof(MESSAGE_MISSILE_HIT))
{
    missile_id = 0;
}

MESSAGE_NOTIFY_ANIM_STOP::MESSAGE_NOTIFY_ANIM_STOP()
    : HEMU_MESSAGE(MSG_NOTIFY_ANIM_STOP, sizeof(MESSAGE_NOTIFY_ANIM_STOP))
{
    entity_id = 0;
}

MESSAGE_NOTIFY_RECPLAYBACK_FRAME::MESSAGE_NOTIFY_RECPLAYBACK_FRAME()
    : HEMU_MESSAGE(MSG_NOTIFY_RECPLAYBACK_FRAME, sizeof(MESSAGE_NOTIFY_RECPLAYBACK_FRAME))
{
}

MESSAGE_WAYPOINT_REACHED::MESSAGE_WAYPOINT_REACHED()
    : HEMU_MESSAGE(MSG_WAYPOINT_REACHED, sizeof(MESSAGE_WAYPOINT_REACHED))
{
    entity_id = 0;
    waypoint_id = 0;
}

MESSAGE_SCRIPT_EOF::MESSAGE_SCRIPT_EOF()
    : HEMU_MESSAGE(MSG_SCRIPT_EOF, sizeof(MESSAGE_SCRIPT_EOF))
{
}

MESSAGE_SCRIPT_PROGRESS::MESSAGE_SCRIPT_PROGRESS()
    : HEMU_MESSAGE(MSG_SCRIPT_PROGRESS, sizeof(MESSAGE_SCRIPT_PROGRESS))
{
    linenum = 0;
}

MESSAGE_DISPLAY_MSG_TEXT::MESSAGE_DISPLAY_MSG_TEXT()
    : HEMU_MESSAGE(MSG_DISPLAY_MSG_TEXT, sizeof(MESSAGE_DISPLAY_MSG_TEXT))
{
    memset(text, '\0', sizeof(text));
}

MESSAGE_UPDATE_ENV_VIEW::MESSAGE_UPDATE_ENV_VIEW()
    : HEMU_MESSAGE(MSG_UPDATE_ENV_VIEW, sizeof(MESSAGE_UPDATE_ENV_VIEW))
{
}

MESSAGE_UPDATE_ENTITIES_VIEW::MESSAGE_UPDATE_ENTITIES_VIEW()
    : HEMU_MESSAGE(MSG_UPDATE_ENTITIES_VIEW, sizeof(MESSAGE_UPDATE_ENTITIES_VIEW))
{
}

MESSAGE_UPDATE_VIEWS_VIEW::MESSAGE_UPDATE_VIEWS_VIEW()
    : HEMU_MESSAGE(MSG_UPDATE_VIEWS_VIEW, sizeof(MESSAGE_UPDATE_VIEWS_VIEW))
{
}

MESSAGE_UPDATE_ENV_TAB_PAGES::MESSAGE_UPDATE_ENV_TAB_PAGES()
    : HEMU_MESSAGE(MSG_UPDATE_ENV_TAB_PAGES, sizeof(MESSAGE_UPDATE_ENV_TAB_PAGES))
{
}

MESSAGE_UPDATE_ENTITY_TAB_PAGES::MESSAGE_UPDATE_ENTITY_TAB_PAGES()
    : HEMU_MESSAGE(MSG_UPDATE_ENTITY_TAB_PAGES, sizeof(MESSAGE_UPDATE_ENTITY_TAB_PAGES))
{
}

MESSAGE_UPDATE_VIEW_TAB_PAGES::MESSAGE_UPDATE_VIEW_TAB_PAGES()
    : HEMU_MESSAGE(MSG_UPDATE_VIEW_TAB_PAGES, sizeof(MESSAGE_UPDATE_VIEW_TAB_PAGES))
{
}

MESSAGE_FORCE_MINOR_VERSION::MESSAGE_FORCE_MINOR_VERSION()
    : HEMU_MESSAGE(MSG_FORCE_MINOR_VERSION, sizeof(MESSAGE_FORCE_MINOR_VERSION))
{
    minor_version = 3;
}

MESSAGE_SYNC_UPDATE_ENV_VIEW::MESSAGE_SYNC_UPDATE_ENV_VIEW()
    : HEMU_MESSAGE(MSG_SYNC_UPDATE_ENV_VIEW, sizeof(MESSAGE_SYNC_UPDATE_ENV_VIEW))
{
}

MESSAGE_SYNC_UPDATE_ENTITIES_VIEW::MESSAGE_SYNC_UPDATE_ENTITIES_VIEW()
    : HEMU_MESSAGE(MSG_SYNC_UPDATE_ENTITIES_VIEW, sizeof(MESSAGE_SYNC_UPDATE_ENTITIES_VIEW))
{
}

MESSAGE_SYNC_UPDATE_VIEWS_VIEW::MESSAGE_SYNC_UPDATE_VIEWS_VIEW()
    : HEMU_MESSAGE(MSG_SYNC_UPDATE_VIEWS_VIEW, sizeof(MESSAGE_SYNC_UPDATE_VIEWS_VIEW))
{
}

MESSAGE_SET_CIGI_OPTIONS::MESSAGE_SET_CIGI_OPTIONS() :
    HEMU_MESSAGE(MSG_SET_CIGI_OPTIONS, sizeof(MESSAGE_SET_CIGI_OPTIONS)),
    big_endian(false),
    major_version(4),
    minor_version(0)
{
}

MESSAGE_TDTEST_START::MESSAGE_TDTEST_START() :
    HEMU_MESSAGE(MSG_TDTEST_START, sizeof(MESSAGE_TDTEST_START)),
    count1(),
    count2(),
    lat1(),
    lon1(),
    alt1(),
    heading1(),
    pitch1(),
    roll1(),
    lat2(),
    lon2(),
    alt2(),
    heading2(),
    pitch2(),
    roll2()
{
}

MESSAGE_TDTEST_STOP::MESSAGE_TDTEST_STOP() :
    HEMU_MESSAGE(MSG_TDTEST_STOP, sizeof(MESSAGE_TDTEST_STOP))
{
}

MESSAGE_SCRIPT_LOAD_SCENARIO::MESSAGE_SCRIPT_LOAD_SCENARIO()
    : HEMU_MESSAGE(MSG_SCRIPT_LOAD_SCENARIO, sizeof(MESSAGE_SCRIPT_LOAD_SCENARIO))
{
    memset(filename, '\0', sizeof(filename));
}

MESSAGE_SCRIPT_SAVE_SCENARIO::MESSAGE_SCRIPT_SAVE_SCENARIO()
    : HEMU_MESSAGE(MSG_SCRIPT_SAVE_SCENARIO, sizeof(MESSAGE_SCRIPT_SAVE_SCENARIO))
{
    memset(filename, '\0', sizeof(filename));
}

MESSAGE_SCRIPT_RELOAD_SCENARIO::MESSAGE_SCRIPT_RELOAD_SCENARIO()
    : HEMU_MESSAGE(MSG_SCRIPT_RELOAD_SCENARIO, sizeof(MESSAGE_SCRIPT_RELOAD_SCENARIO))
{
}

MESSAGE_SCRIPT_CAPTURE_PLAY::MESSAGE_SCRIPT_CAPTURE_PLAY()
    : HEMU_MESSAGE(MSG_SCRIPT_CAPTURE_PLAY, sizeof(MESSAGE_SCRIPT_CAPTURE_PLAY))
{
    memset(filename, '\0', sizeof(filename));
}

MESSAGE_CLEAR_MSG_TEXT::MESSAGE_CLEAR_MSG_TEXT()
    : HEMU_MESSAGE(MSG_CLEAR_MSG_TEXT, sizeof(MESSAGE_CLEAR_MSG_TEXT))
{
}

MESSAGE_UPDATE_DATABASE::MESSAGE_UPDATE_DATABASE()
    : HEMU_MESSAGE(MSG_UPDATE_DATABASE, sizeof(MESSAGE_UPDATE_DATABASE))
{
    db_num = 0;
}

MESSAGE_SPAWN_APP::MESSAGE_SPAWN_APP()
    : HEMU_MESSAGE(MSG_SPAWN_APP, sizeof(MESSAGE_SPAWN_APP))
{
    memset(command, '\0', sizeof(command));
}

MESSAGE_SCRIPT_BEGIN_WAIT_TIMER::MESSAGE_SCRIPT_BEGIN_WAIT_TIMER()
    : HEMU_MESSAGE(MSG_SCRIPT_BEGIN_WAIT_TIMER, sizeof(MESSAGE_SCRIPT_BEGIN_WAIT_TIMER))
{
    secs = 0;
}

MESSAGE_SCRIPT_INC_WAIT_TIMER::MESSAGE_SCRIPT_INC_WAIT_TIMER()
    : HEMU_MESSAGE(MSG_SCRIPT_INC_WAIT_TIMER, sizeof(MESSAGE_SCRIPT_INC_WAIT_TIMER))
{
    secs = 0;
}

MESSAGE_SCRIPT_END_WAIT_TIMER::MESSAGE_SCRIPT_END_WAIT_TIMER()
    : HEMU_MESSAGE(MSG_SCRIPT_END_WAIT_TIMER, sizeof(MESSAGE_SCRIPT_END_WAIT_TIMER))
{
}

MESSAGE_SCRIPT_ADD_ENTITY_TO_GUI::MESSAGE_SCRIPT_ADD_ENTITY_TO_GUI()
    : HEMU_MESSAGE(MSG_SCRIPT_ADD_ENTITY_TO_GUI, sizeof(MESSAGE_SCRIPT_ADD_ENTITY_TO_GUI))
{
    entity_id = -1;
}

MESSAGE_SCRIPT_DEL_ENTITY_FROM_GUI::MESSAGE_SCRIPT_DEL_ENTITY_FROM_GUI()
    : HEMU_MESSAGE(MSG_SCRIPT_DEL_ENTITY_FROM_GUI, sizeof(MESSAGE_SCRIPT_DEL_ENTITY_FROM_GUI))
{
    entity_id = -1;
    htree = 0;
    htree_env = 0;
    situation_hdl = 0;
}

MESSAGE_SCRIPT_SET_PARENT_IN_GUI::MESSAGE_SCRIPT_SET_PARENT_IN_GUI()
    : HEMU_MESSAGE(MSG_SCRIPT_SET_PARENT_IN_GUI, sizeof(MESSAGE_SCRIPT_SET_PARENT_IN_GUI))
{
    entity_id = -1;
    parent_id = -1;
}

MESSAGE_SCRIPT_SET_VIEWGROUP_IN_GUI::MESSAGE_SCRIPT_SET_VIEWGROUP_IN_GUI()
    : HEMU_MESSAGE(MSG_SCRIPT_SET_VIEWGROUP_IN_GUI, sizeof(MESSAGE_SCRIPT_SET_VIEWGROUP_IN_GUI))
{
    view_id = -1;
    group_id = 0;
}

MESSAGE_SCRIPT_SET_PAUSE::MESSAGE_SCRIPT_SET_PAUSE()
    : HEMU_MESSAGE(MSG_SCRIPT_SET_PAUSE, sizeof(MESSAGE_SCRIPT_SET_PAUSE))
{
}

MESSAGE_SCRIPT_FIRE_MISSILE::MESSAGE_SCRIPT_FIRE_MISSILE()
    : HEMU_MESSAGE(MSG_SCRIPT_FIRE_MISSILE, sizeof(MESSAGE_SCRIPT_FIRE_MISSILE))
{
    pMissile = NULL;
}

MESSAGE_SCRIPT_UPDATE_MISSILE_TARGET_COMBO::MESSAGE_SCRIPT_UPDATE_MISSILE_TARGET_COMBO()
    : HEMU_MESSAGE(MSG_SCRIPT_UPDATE_MISSILE_TARGET_COMBO, sizeof(MESSAGE_SCRIPT_UPDATE_MISSILE_TARGET_COMBO))
{
}
