#include "Cigi3Api.h"

// The upstream CIGI 3 API intentionally mirrors the CIGI 4 API names
// (CigiInit, CigiCreateSession, CIGI_IG_CONTROL, CIGI_*_OPCODE, etc.).
// Compile the upstream implementation in this private translation unit with
// renamed public functions so it can coexist in the same executable as the
// existing CIGI 4 implementation. Do not include the raw CIGI 3 headers from
// app/driver code; expose CIGI 3 behavior through adapter-owned wrappers.
#define CigiAddFixedPacket Cigi3Legacy_CigiAddFixedPacket
#define CigiAddPacketIGCtrl Cigi3Legacy_CigiAddPacketIGCtrl
#define CigiAddPacketIGMessage Cigi3Legacy_CigiAddPacketIGMessage
#define CigiAddPacketReplaceAerosolResp Cigi3Legacy_CigiAddPacketReplaceAerosolResp
#define CigiAddPacketReplaceAnimationStopNotification Cigi3Legacy_CigiAddPacketReplaceAnimationStopNotification
#define CigiAddPacketReplaceArtPartCtrl Cigi3Legacy_CigiAddPacketReplaceArtPartCtrl
#define CigiAddPacketReplaceAtmosphereCtrl Cigi3Legacy_CigiAddPacketReplaceAtmosphereCtrl
#define CigiAddPacketReplaceCCEntityCtrl Cigi3Legacy_CigiAddPacketReplaceCCEntityCtrl
#define CigiAddPacketReplaceCelestialSphereCtrl Cigi3Legacy_CigiAddPacketReplaceCelestialSphereCtrl
#define CigiAddPacketReplaceCollDetSegmentDef Cigi3Legacy_CigiAddPacketReplaceCollDetSegmentDef
#define CigiAddPacketReplaceCollDetSegmentNotification Cigi3Legacy_CigiAddPacketReplaceCollDetSegmentNotification
#define CigiAddPacketReplaceCollDetVolumeDef Cigi3Legacy_CigiAddPacketReplaceCollDetVolumeDef
#define CigiAddPacketReplaceCollDetVolumeNotification Cigi3Legacy_CigiAddPacketReplaceCollDetVolumeNotification
#define CigiAddPacketReplaceComponentCtrl32 Cigi3Legacy_CigiAddPacketReplaceComponentCtrl32
#define CigiAddPacketReplaceComponentCtrl33 Cigi3Legacy_CigiAddPacketReplaceComponentCtrl33
#define CigiAddPacketReplaceEntityCtrl Cigi3Legacy_CigiAddPacketReplaceEntityCtrl
#define CigiAddPacketReplaceEnvConditionsReq Cigi3Legacy_CigiAddPacketReplaceEnvConditionsReq
#define CigiAddPacketReplaceEnvRegionCtrl Cigi3Legacy_CigiAddPacketReplaceEnvRegionCtrl
#define CigiAddPacketReplaceErmDef Cigi3Legacy_CigiAddPacketReplaceErmDef
#define CigiAddPacketReplaceEventNotification Cigi3Legacy_CigiAddPacketReplaceEventNotification
#define CigiAddPacketReplaceHatExtResp Cigi3Legacy_CigiAddPacketReplaceHatExtResp
#define CigiAddPacketReplaceHatHotReq Cigi3Legacy_CigiAddPacketReplaceHatHotReq
#define CigiAddPacketReplaceHatResp Cigi3Legacy_CigiAddPacketReplaceHatResp
#define CigiAddPacketReplaceLosExtResp Cigi3Legacy_CigiAddPacketReplaceLosExtResp
#define CigiAddPacketReplaceLosResp Cigi3Legacy_CigiAddPacketReplaceLosResp
#define CigiAddPacketReplaceLosSegmentReq Cigi3Legacy_CigiAddPacketReplaceLosSegmentReq
#define CigiAddPacketReplaceLosVectorReq Cigi3Legacy_CigiAddPacketReplaceLosVectorReq
#define CigiAddPacketReplaceMaritimeCondCtrl Cigi3Legacy_CigiAddPacketReplaceMaritimeCondCtrl
#define CigiAddPacketReplaceMaritimeCondResp Cigi3Legacy_CigiAddPacketReplaceMaritimeCondResp
#define CigiAddPacketReplaceMotionTrackerCtrl Cigi3Legacy_CigiAddPacketReplaceMotionTrackerCtrl
#define CigiAddPacketReplacePositionReq Cigi3Legacy_CigiAddPacketReplacePositionReq
#define CigiAddPacketReplacePositionResp Cigi3Legacy_CigiAddPacketReplacePositionResp
#define CigiAddPacketReplaceRateCtrl Cigi3Legacy_CigiAddPacketReplaceRateCtrl
#define CigiAddPacketReplaceSensorCtrl Cigi3Legacy_CigiAddPacketReplaceSensorCtrl
#define CigiAddPacketReplaceSensorExtResp Cigi3Legacy_CigiAddPacketReplaceSensorExtResp
#define CigiAddPacketReplaceSensorResp Cigi3Legacy_CigiAddPacketReplaceSensorResp
#define CigiAddPacketReplaceShortArtPartCtrl Cigi3Legacy_CigiAddPacketReplaceShortArtPartCtrl
#define CigiAddPacketReplaceShortComponentCtrl32 Cigi3Legacy_CigiAddPacketReplaceShortComponentCtrl32
#define CigiAddPacketReplaceShortComponentCtrl33 Cigi3Legacy_CigiAddPacketReplaceShortComponentCtrl33
#define CigiAddPacketReplaceShortSymbolCtrl Cigi3Legacy_CigiAddPacketReplaceShortSymbolCtrl
#define CigiAddPacketReplaceSymbolCircleDef Cigi3Legacy_CigiAddPacketReplaceSymbolCircleDef
#define CigiAddPacketReplaceSymbolClone Cigi3Legacy_CigiAddPacketReplaceSymbolClone
#define CigiAddPacketReplaceSymbolCtrl Cigi3Legacy_CigiAddPacketReplaceSymbolCtrl
#define CigiAddPacketReplaceSymbolLineDef Cigi3Legacy_CigiAddPacketReplaceSymbolLineDef
#define CigiAddPacketReplaceSymbolSurfaceDef Cigi3Legacy_CigiAddPacketReplaceSymbolSurfaceDef
#define CigiAddPacketReplaceSymbolTextDef Cigi3Legacy_CigiAddPacketReplaceSymbolTextDef
#define CigiAddPacketReplaceTerrestrialCondCtrl Cigi3Legacy_CigiAddPacketReplaceTerrestrialCondCtrl
#define CigiAddPacketReplaceTerrestrialCondResp Cigi3Legacy_CigiAddPacketReplaceTerrestrialCondResp
#define CigiAddPacketReplaceTrajectoryDef Cigi3Legacy_CigiAddPacketReplaceTrajectoryDef
#define CigiAddPacketReplaceViewCtrl Cigi3Legacy_CigiAddPacketReplaceViewCtrl
#define CigiAddPacketReplaceViewDef Cigi3Legacy_CigiAddPacketReplaceViewDef
#define CigiAddPacketReplaceWaveCtrl Cigi3Legacy_CigiAddPacketReplaceWaveCtrl
#define CigiAddPacketReplaceWeatherCtrl Cigi3Legacy_CigiAddPacketReplaceWeatherCtrl
#define CigiAddPacketReplaceWeatherResp Cigi3Legacy_CigiAddPacketReplaceWeatherResp
#define CigiAddPacketSof Cigi3Legacy_CigiAddPacketSof
#define CigiAddReplaceFixedPacket Cigi3Legacy_CigiAddReplaceFixedPacket
#define CigiCloseSession Cigi3Legacy_CigiCloseSession
#define CigiCreateSession Cigi3Legacy_CigiCreateSession
#define CigiEndMessage Cigi3Legacy_CigiEndMessage
#define CigiGetFirstPacket Cigi3Legacy_CigiGetFirstPacket
#define CigiGetIncomingMsgBuffer Cigi3Legacy_CigiGetIncomingMsgBuffer
#define CigiGetMinorVersion Cigi3Legacy_CigiGetMinorVersion
#define CigiGetNextPacket Cigi3Legacy_CigiGetNextPacket
#define CigiGetOutgoingMsgBuffer Cigi3Legacy_CigiGetOutgoingMsgBuffer
#define CigiInit Cigi3Legacy_CigiInit
#define CigiProcessIncomingMsgBuffer Cigi3Legacy_CigiProcessIncomingMsgBuffer
#define CigiSearchForPacket Cigi3Legacy_CigiSearchForPacket
#define CigiSetCallback Cigi3Legacy_CigiSetCallback
#define CigiSetDefaultCallback Cigi3Legacy_CigiSetDefaultCallback
#define CigiSetIncomingMsgBuffer Cigi3Legacy_CigiSetIncomingMsgBuffer
#define CigiSetMinorVersion Cigi3Legacy_CigiSetMinorVersion
#define CigiShutdown Cigi3Legacy_CigiShutdown
#define CigiStartMessage Cigi3Legacy_CigiStartMessage
#define CigiSwap2 Cigi3Legacy_CigiSwap2
#define CigiSwap4 Cigi3Legacy_CigiSwap4
#define CigiSwap8 Cigi3Legacy_CigiSwap8
#define CigiSwapOutgoingMsgBuffer Cigi3Legacy_CigiSwapOutgoingMsgBuffer
#define CigiSwapPacketAerosolResp Cigi3Legacy_CigiSwapPacketAerosolResp
#define CigiSwapPacketAnimationStopNotification Cigi3Legacy_CigiSwapPacketAnimationStopNotification
#define CigiSwapPacketArtPartCtrl Cigi3Legacy_CigiSwapPacketArtPartCtrl
#define CigiSwapPacketAtmosphereCtrl Cigi3Legacy_CigiSwapPacketAtmosphereCtrl
#define CigiSwapPacketCCEntityCtrl Cigi3Legacy_CigiSwapPacketCCEntityCtrl
#define CigiSwapPacketCelestialSphereCtrl Cigi3Legacy_CigiSwapPacketCelestialSphereCtrl
#define CigiSwapPacketCollSegmentDef Cigi3Legacy_CigiSwapPacketCollSegmentDef
#define CigiSwapPacketCollSegmentNotification Cigi3Legacy_CigiSwapPacketCollSegmentNotification
#define CigiSwapPacketCollVolumeDef Cigi3Legacy_CigiSwapPacketCollVolumeDef
#define CigiSwapPacketCollVolumeNotification Cigi3Legacy_CigiSwapPacketCollVolumeNotification
#define CigiSwapPacketComponentCtrl Cigi3Legacy_CigiSwapPacketComponentCtrl
#define CigiSwapPacketEntityCtrl Cigi3Legacy_CigiSwapPacketEntityCtrl
#define CigiSwapPacketEnvCondReq Cigi3Legacy_CigiSwapPacketEnvCondReq
#define CigiSwapPacketEnvRegionCtrl Cigi3Legacy_CigiSwapPacketEnvRegionCtrl
#define CigiSwapPacketErmDef Cigi3Legacy_CigiSwapPacketErmDef
#define CigiSwapPacketEventNotification Cigi3Legacy_CigiSwapPacketEventNotification
#define CigiSwapPacketHatHotExtResp Cigi3Legacy_CigiSwapPacketHatHotExtResp
#define CigiSwapPacketHatHotReq Cigi3Legacy_CigiSwapPacketHatHotReq
#define CigiSwapPacketHatHotResp Cigi3Legacy_CigiSwapPacketHatHotResp
#define CigiSwapPacketIGMessage Cigi3Legacy_CigiSwapPacketIGMessage
#define CigiSwapPacketLosExtResp Cigi3Legacy_CigiSwapPacketLosExtResp
#define CigiSwapPacketLosResp Cigi3Legacy_CigiSwapPacketLosResp
#define CigiSwapPacketLosSegmentReq Cigi3Legacy_CigiSwapPacketLosSegmentReq
#define CigiSwapPacketLosVectorReq Cigi3Legacy_CigiSwapPacketLosVectorReq
#define CigiSwapPacketMaritimeCondCtrl Cigi3Legacy_CigiSwapPacketMaritimeCondCtrl
#define CigiSwapPacketMaritimeCondResp Cigi3Legacy_CigiSwapPacketMaritimeCondResp
#define CigiSwapPacketMotionTrackerCtrl Cigi3Legacy_CigiSwapPacketMotionTrackerCtrl
#define CigiSwapPacketPositionReq Cigi3Legacy_CigiSwapPacketPositionReq
#define CigiSwapPacketPositionResp Cigi3Legacy_CigiSwapPacketPositionResp
#define CigiSwapPacketRateCtrl Cigi3Legacy_CigiSwapPacketRateCtrl
#define CigiSwapPacketSensorCtrl Cigi3Legacy_CigiSwapPacketSensorCtrl
#define CigiSwapPacketSensorExtResp Cigi3Legacy_CigiSwapPacketSensorExtResp
#define CigiSwapPacketSensorResp Cigi3Legacy_CigiSwapPacketSensorResp
#define CigiSwapPacketShortArtPartCtrl Cigi3Legacy_CigiSwapPacketShortArtPartCtrl
#define CigiSwapPacketShortComponentCtrl Cigi3Legacy_CigiSwapPacketShortComponentCtrl
#define CigiSwapPacketShortSymbolCtrl Cigi3Legacy_CigiSwapPacketShortSymbolCtrl
#define CigiSwapPacketSymbolCircleDef Cigi3Legacy_CigiSwapPacketSymbolCircleDef
#define CigiSwapPacketSymbolClone Cigi3Legacy_CigiSwapPacketSymbolClone
#define CigiSwapPacketSymbolCtrl Cigi3Legacy_CigiSwapPacketSymbolCtrl
#define CigiSwapPacketSymbolLineDef Cigi3Legacy_CigiSwapPacketSymbolLineDef
#define CigiSwapPacketSymbolSurfaceDef Cigi3Legacy_CigiSwapPacketSymbolSurfaceDef
#define CigiSwapPacketSymbolTextDef Cigi3Legacy_CigiSwapPacketSymbolTextDef
#define CigiSwapPacketTerrestrialCondCtrl Cigi3Legacy_CigiSwapPacketTerrestrialCondCtrl
#define CigiSwapPacketTerrestrialCondResp Cigi3Legacy_CigiSwapPacketTerrestrialCondResp
#define CigiSwapPacketTrajectoryDef Cigi3Legacy_CigiSwapPacketTrajectoryDef
#define CigiSwapPacketUserData Cigi3Legacy_CigiSwapPacketUserData
#define CigiSwapPacketViewCtrl Cigi3Legacy_CigiSwapPacketViewCtrl
#define CigiSwapPacketViewDef Cigi3Legacy_CigiSwapPacketViewDef
#define CigiSwapPacketWaveCtrl Cigi3Legacy_CigiSwapPacketWaveCtrl
#define CigiSwapPacketWeatherCtrl Cigi3Legacy_CigiSwapPacketWeatherCtrl
#define CigiSwapPacketWeatherResp Cigi3Legacy_CigiSwapPacketWeatherResp
#define CigiSyncFrameCounter Cigi3Legacy_CigiSyncFrameCounter
#define PrepareSessionAndGetPtr Cigi3Legacy_PrepareSessionAndGetPtr

#include "legacy/cigi3.cpp"

#undef CigiAddFixedPacket
#undef CigiAddPacketIGCtrl
#undef CigiAddPacketIGMessage
#undef CigiAddPacketReplaceAerosolResp
#undef CigiAddPacketReplaceAnimationStopNotification
#undef CigiAddPacketReplaceArtPartCtrl
#undef CigiAddPacketReplaceAtmosphereCtrl
#undef CigiAddPacketReplaceCCEntityCtrl
#undef CigiAddPacketReplaceCelestialSphereCtrl
#undef CigiAddPacketReplaceCollDetSegmentDef
#undef CigiAddPacketReplaceCollDetSegmentNotification
#undef CigiAddPacketReplaceCollDetVolumeDef
#undef CigiAddPacketReplaceCollDetVolumeNotification
#undef CigiAddPacketReplaceComponentCtrl32
#undef CigiAddPacketReplaceComponentCtrl33
#undef CigiAddPacketReplaceEntityCtrl
#undef CigiAddPacketReplaceEnvConditionsReq
#undef CigiAddPacketReplaceEnvRegionCtrl
#undef CigiAddPacketReplaceErmDef
#undef CigiAddPacketReplaceEventNotification
#undef CigiAddPacketReplaceHatExtResp
#undef CigiAddPacketReplaceHatHotReq
#undef CigiAddPacketReplaceHatResp
#undef CigiAddPacketReplaceLosExtResp
#undef CigiAddPacketReplaceLosResp
#undef CigiAddPacketReplaceLosSegmentReq
#undef CigiAddPacketReplaceLosVectorReq
#undef CigiAddPacketReplaceMaritimeCondCtrl
#undef CigiAddPacketReplaceMaritimeCondResp
#undef CigiAddPacketReplaceMotionTrackerCtrl
#undef CigiAddPacketReplacePositionReq
#undef CigiAddPacketReplacePositionResp
#undef CigiAddPacketReplaceRateCtrl
#undef CigiAddPacketReplaceSensorCtrl
#undef CigiAddPacketReplaceSensorExtResp
#undef CigiAddPacketReplaceSensorResp
#undef CigiAddPacketReplaceShortArtPartCtrl
#undef CigiAddPacketReplaceShortComponentCtrl32
#undef CigiAddPacketReplaceShortComponentCtrl33
#undef CigiAddPacketReplaceShortSymbolCtrl
#undef CigiAddPacketReplaceSymbolCircleDef
#undef CigiAddPacketReplaceSymbolClone
#undef CigiAddPacketReplaceSymbolCtrl
#undef CigiAddPacketReplaceSymbolLineDef
#undef CigiAddPacketReplaceSymbolSurfaceDef
#undef CigiAddPacketReplaceSymbolTextDef
#undef CigiAddPacketReplaceTerrestrialCondCtrl
#undef CigiAddPacketReplaceTerrestrialCondResp
#undef CigiAddPacketReplaceTrajectoryDef
#undef CigiAddPacketReplaceViewCtrl
#undef CigiAddPacketReplaceViewDef
#undef CigiAddPacketReplaceWaveCtrl
#undef CigiAddPacketReplaceWeatherCtrl
#undef CigiAddPacketReplaceWeatherResp
#undef CigiAddPacketSof
#undef CigiAddReplaceFixedPacket
#undef CigiCloseSession
#undef CigiCreateSession
#undef CigiEndMessage
#undef CigiGetFirstPacket
#undef CigiGetIncomingMsgBuffer
#undef CigiGetMinorVersion
#undef CigiGetNextPacket
#undef CigiGetOutgoingMsgBuffer
#undef CigiInit
#undef CigiProcessIncomingMsgBuffer
#undef CigiSearchForPacket
#undef CigiSetCallback
#undef CigiSetDefaultCallback
#undef CigiSetIncomingMsgBuffer
#undef CigiSetMinorVersion
#undef CigiShutdown
#undef CigiStartMessage
#undef CigiSwap2
#undef CigiSwap4
#undef CigiSwap8
#undef CigiSwapOutgoingMsgBuffer
#undef CigiSwapPacketAerosolResp
#undef CigiSwapPacketAnimationStopNotification
#undef CigiSwapPacketArtPartCtrl
#undef CigiSwapPacketAtmosphereCtrl
#undef CigiSwapPacketCCEntityCtrl
#undef CigiSwapPacketCelestialSphereCtrl
#undef CigiSwapPacketCollSegmentDef
#undef CigiSwapPacketCollSegmentNotification
#undef CigiSwapPacketCollVolumeDef
#undef CigiSwapPacketCollVolumeNotification
#undef CigiSwapPacketComponentCtrl
#undef CigiSwapPacketEntityCtrl
#undef CigiSwapPacketEnvCondReq
#undef CigiSwapPacketEnvRegionCtrl
#undef CigiSwapPacketErmDef
#undef CigiSwapPacketEventNotification
#undef CigiSwapPacketHatHotExtResp
#undef CigiSwapPacketHatHotReq
#undef CigiSwapPacketHatHotResp
#undef CigiSwapPacketIGMessage
#undef CigiSwapPacketLosExtResp
#undef CigiSwapPacketLosResp
#undef CigiSwapPacketLosSegmentReq
#undef CigiSwapPacketLosVectorReq
#undef CigiSwapPacketMaritimeCondCtrl
#undef CigiSwapPacketMaritimeCondResp
#undef CigiSwapPacketMotionTrackerCtrl
#undef CigiSwapPacketPositionReq
#undef CigiSwapPacketPositionResp
#undef CigiSwapPacketRateCtrl
#undef CigiSwapPacketSensorCtrl
#undef CigiSwapPacketSensorExtResp
#undef CigiSwapPacketSensorResp
#undef CigiSwapPacketShortArtPartCtrl
#undef CigiSwapPacketShortComponentCtrl
#undef CigiSwapPacketShortSymbolCtrl
#undef CigiSwapPacketSymbolCircleDef
#undef CigiSwapPacketSymbolClone
#undef CigiSwapPacketSymbolCtrl
#undef CigiSwapPacketSymbolLineDef
#undef CigiSwapPacketSymbolSurfaceDef
#undef CigiSwapPacketSymbolTextDef
#undef CigiSwapPacketTerrestrialCondCtrl
#undef CigiSwapPacketTerrestrialCondResp
#undef CigiSwapPacketTrajectoryDef
#undef CigiSwapPacketUserData
#undef CigiSwapPacketViewCtrl
#undef CigiSwapPacketViewDef
#undef CigiSwapPacketWaveCtrl
#undef CigiSwapPacketWeatherCtrl
#undef CigiSwapPacketWeatherResp
#undef CigiSyncFrameCounter
#undef PrepareSessionAndGetPtr

namespace cigi3
{
const ApiInfo &GetApiInfo()
{
    static const ApiInfo info = {
        CIGI_VERSION,
        CIGI_MAX_PACKET_SIZE,
        CIGI_MAX_SESSIONS,
        CIGI_HOST_SESSION,
        CIGI_IG_SESSION
    };

    return info;
}

bool IsLegacyApiLinked()
{
    return &Cigi3Legacy_CigiInit != 0 &&
           &Cigi3Legacy_CigiCreateSession != 0 &&
           &Cigi3Legacy_CigiShutdown != 0;
}
}
