//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Hemu4.rc
//
#define ID_CONFIG_TOOLBAR               1
#define ID_CONFIG_ENTITY_OPTIONTREE     2
#define IDC_EDIT_ENTITY_ALPHA           8
#define IDC_EDIT_ENTITY_ALTITUDE        9
#define IDC_EDIT_ENTITY_BEARING         10
#define IDC_EDIT_ENTITY_LATITUDE        11
#define IDC_EDIT_ENTITY_LONGITUDE       12
#define IDC_EDIT_ENTITY_PITCH           13
#define IDC_EDIT_ENTITY_RANGE           14
#define IDC_EDIT_ENTITY_ROLL            15
#define IDC_EDIT_ENTITY_SPEED           16
#define IDC_EDIT_ENTITY_YAW             17
#define IDC_EDIT_ENTITY_OPACITY         18
#define IDC_EDIT_ENTITY_TEMPERATURE     19
#define IDC_EDIT_ENTITY_ID              20
#define IDC_EDIT_ENTITY_TYPE            21
#define IDD_ABOUTBOX                    100
#define IDD_ENTITY_STATE_VIEW           101
#define IDD_ENTITY_PROPS_ARTPARTS       102
#define IDD_OUTPUT_VIEW                 103
#define IDD_WATCH_VIEW                  104
#define IDD_MESSAGE_VIEW                105
#define IDD_PROPPAGE_ENTITY_COMPONENTS  106
#define IDR_HTML_PACKETDLGSYMBOLSURFACEDEF 107
#define IDR_MAINFRAME                   128
#define IDR_CONFIGURATION               129
#define IDR_HEMU3TYPE                   129
#define IDD_DIALOG_DATETIME             132
#define IDD_SITUATIONVIEW               133
#define IDB_ORTHOGRAPHIC                134
#define IDD_NAVIGATIONVIEW              134
#define IDD_OBJECT_TREE_VIEW            134
#define IDD_BLANK_TREE_VIEW             135
#define IDD_NAVTREEVIEW                 135
#define IDD_VIEW_STATE_VIEW             136
#define IDI_CONFIG                      136
#define IDB_CONFIG_TOOLBAR              137
#define IDD_VIEWGROUP_STATE_VIEW        137
#define IDB_PERSPECTIVE                 138
#define IDC_SPLITTER                    138
#define IDD_REGION_STATE_VIEW           138
#define IDD_WEATHER_STATE_VIEW          139
#define IDD_BLANK_STATE_VIEW            140
#define IDD_GLOBALENV_STATE_VIEW        141
#define IDD_GROUND_STATE_VIEW           142
#define IDD_SEA_STATE_VIEW              143
#define IDD_ATMOSPHERE_STATE_VIEW       144
#define IDD_VIEW_CONFIGURATION          145
#define IDD_DIALOG_NEW_ENTITY           146
#define IDD_DIALOG_SETUP                147
#define IDD_DIALOG_FLY                  148
#define IDD_PROPPAGE_ENTITY_ARTPARTS    149
#define IDD_PROPPAGE_ENTITY_HATHOT      150
#define IDD_PROPPAGE_ENTITY_LOS         151
#define IDR_TOOLBAR_NOT_USED            151
#define IDD_PROPPAGE_ENTITY_COLLDET     152
#define IDD_PROPPAGE_ENTITY_MISSILE     153
#define IDD_DIALOG_RECPLAYBACK          154
#define IDD_DIALOG_PACKET_FILTER        155
#define IDB_ICONS                       156
#define IDD_FILTER_PAGE_INCOMING        156
#define IDD_FILTER_PAGE_OUTGOING        157
#define IDD_DIALOG_HISTORY              158
#define IDD_SKY_STATE_VIEW              159
#define IDB_ENTITY_TYPES                160
#define IDD_TERRAIN_STATE_VIEW          160
#define IDD_DIALOGBAR                   161
#define IDD_PROPPAGE_ENTITY_WEATHER     162
#define IDI_PLAY                        162
#define IDD_PROPPAGE_VIEW_FRUSTUM       163
#define IDI_RECORD                      163
#define IDD_DIALOG_SCRIPT               164
#define IDI_STOP                        164
#define IDD_PACKET_IG_CONTROL           165
#define IDI_PAUSE                       165
#define IDI_LOOP                        166
#define IDD_PACKET_ENTITY_POSITION      166
#define IDD_PACKET_CLAMPED_ENTITY_POSITION 167
#define IDD_PACKET_COMPONENT_CONTROL    168
#define IDD_PACKET_SHORT_COMPONENT_CONTROL 169
#define IDD_PACKET_ARTPART_CONTROL      170
#define IDD_PACKET_SHORT_ARTPART_CONTROL 171
#define IDD_PACKET_VELOCITY_CONTROL     172
#define IDD_PACKET_CELESTIAL_SPHERE_CONTROL 173
#define IDD_PACKET_ATMOSPHERE_CONTROL   174
#define IDD_PACKET_ENV_REGION_CONTROL   175
#define IDD_PACKET_WEATHER_CONTROL      176
#define IDD_PACKET_MARITIME_CONTROL     177
#define IDD_PACKET_TERRESTRIAL_CONTROL  178
#define IDD_PACKET_WAVE_CONTROL         179
#define IDD_PACKET_VIEW_CONTROL         180
#define IDD_PACKET_SENSOR_CONTROL       181
#define IDD_PACKET_MOTION_TRACKER_CONTROL 182
#define IDD_PACKET_ERM_DEF              183
#define IDD_PACKET_TRAJECTORY_DEF       184
#define IDD_PACKET_ACCELERATION_CONTROL 184
#define IDD_PACKET_VIEW_DEF             185
#define IDD_PACKET_CD_SEGMENT_DEF       186
#define IDD_PACKET_CD_VOLUME_DEF        187
#define IDD_PACKET_HAT_HOT_REQ          188
#define IDD_PACKET_LOS_SEGMENT_REQ      189
#define IDD_PACKET_LOS_VECTOR_REQ       190
#define IDD_PACKET_POSITION_REQ         191
#define IDD_PACKET_ENV_CONDITIONS_REQ   192
#define IDD_PACKET_SYMBOL_DEF           193
#define IDD_PACKET_SYMBOL_SURFACE_DEF   193
#define IDD_PACKET_SYMBOL_TEXT_DEF      194
#define IDD_PACKET_SYMBOL_CIRCLE_DEF    195
#define IDD_PACKET_SYMBOL_POLYGON_DEF   196
#define IDD_PACKET_SYMBOL_CONTROL       197
#define IDD_PACKET_SHORT_SYMBOL_CONTROL 198
#define IDD_DIALOG1                     200
#define IDD_PACKET_SYMBOL_CLONE         200
#define IDD_PACKET_ENTITY_CONTROL       201
#define IDD_PACKET_ANIMATION_CONTROL    202
#define IDD_PACKET_SYMBOL_TEXTURED_CIRCLE_DEF 203
#define IDD_PACKET_SYMBOL_TEXTURED_POLYGON_DEF 204
#define IDC_VERSION_INFO                1000
#define IDC_COMBOBOXEX_ENTITY_TYPE      1002
#define IDC_COMBOBOXEX_ENTITY_PARENT    1003
#define IDC_CHECK_ARTPARTS_X            1004
#define IDC_EDIT_VIEWPOS_X              1004
#define IDC_LABEL_ENTITY_LATITUDE       1004
#define IDC_EDIT_VIEWPOS_Y              1005
#define IDC_LABEL_ENTITY_LONGITUDE      1005
#define IDC_CHECK_ARTPARTS_Y            1006
#define IDC_LABEL_ENTITY_ALTITUDE       1006
#define IDC_CHECK_ARTPARTS_Z            1007
#define IDC_CHECK_ARTPARTS_YAW          1009
#define IDC_CHECK_ARTPARTS_PITCH        1010
#define IDC_LABEL_ENTITY_LAT_UNIT       1010
#define IDC_BUTTON_FIRE                 1011
#define IDC_CHECK_ARTPARTS_ROLL         1011
#define IDC_COMBOBOXEX_ENTITY_RELATIVE_TO 1011
#define IDC_LABEL_SPEED                 1014
#define IDC_LABEL_ENTITY_LON_UNIT       1016
#define IDC_LABEL_ENTITY_ALT_UNIT       1017
#define IDC_LABEL_SPEED_UNIT            1018
#define IDC_CHECK_ENTITY_INHERIT_ALPHA  1023
#define IDC_CHECK_ENTITY_INHERIT_OPACITY 1023
#define IDC_CHECK_ENTITY_HIDE_GEOMETRY  1024
#define IDC_RADIO_ENTITY_GROUND_CLAMP_ALT 1028
#define IDC_RADIO_ENTITY_GROUND_CLAMP_ALT_AND_ATT 1029
#define IDC_CHECK_ENTITY_ANIMATION_REVERSE 1030
#define IDC_CHECK_ENTITY_ANIMATION_LOOP 1031
#define IDC_CHECK_ENTITY_FLY_WAYPOINTS  1032
#define IDC_SPIN_ARTPARTS_P             1032
#define IDC_CHECK_ENTITY_RATES          1033
#define IDC_CHECK_ENTITY_GROUND_CLAMP   1034
#define IDC_RADIO_ENTITY_GROUND_CLAMP_NONE 1034
#define IDC_SPIN_ARTPARTS_R             1035
#define IDC_TAB1                        1035
#define IDC_LIST_ARTPARTS_PARTS         1037
#define IDC_SPIN_ARTPARTS_Y             1038
#define IDC_LIST1                       1039
#define IDC_SPIN_ARTPARTS_Z             1039
#define IDC_EDIT1                       1040
#define IDC_DATETIME_DATE               1041
#define IDC_EDIT2                       1041
#define IDC_DATETIME_TIME               1042
#define IDC_EDIT3                       1042
#define IDC_CHECK_EPHEMERIS             1043
#define IDC_EDIT4                       1043
#define IDC_CHECK_SUN                   1044
#define IDC_EDIT5                       1044
#define IDC_CHECK_MOON                  1045
#define IDC_EDIT6                       1045
#define IDC_CHECK_STARFIELD             1046
#define IDC_EDIT7                       1046
#define IDC_EDIT8                       1047
#define IDC_EDIT_PERIMETER              1047
#define IDC_EDIT_STARFIELD_INTENSITY    1047
#define IDC_EDIT10                      1048
#define IDC_SITUATION_CTRL              1048
#define IDC_EDIT11                      1049
#define IDC_TAB_NAV                     1049
#define IDC_EDIT12                      1050
#define IDC_TREE                        1050
#define IDC_EDIT13                      1051
#define IDC_RADIO1                      1052
#define IDC_RADIO_CLASS_ENTITY          1052
#define IDC_RADIO_GLOBAL                1052
#define IDC_RADIO_MARITIME              1052
#define IDC_RADIO_MODE_RESET            1052
#define IDC_RADIO_PARENT                1052
#define IDC_RADIO_RATES_PARENT          1052
#define IDC_RADIO_STATE_INACTIVE        1052
#define IDC_RADIO_TYPE_HAT              1052
#define IDC_RADIO_TYPE_SPHERE           1052
#define IDC_RADIO2                      1053
#define IDC_RADIO_CLASS_ARTPART         1053
#define IDC_RADIO_LOCAL                 1053
#define IDC_RADIO_MODE_OPERATE          1053
#define IDC_RADIO_RATES_LOCAL           1053
#define IDC_RADIO_REGIONAL              1053
#define IDC_RADIO_REGION_STATE_ACTIVE   1053
#define IDC_RADIO_TERRESTRIAL           1053
#define IDC_RADIO_TYPE_CUBOID           1053
#define IDC_RADIO_TYPE_HOT              1053
#define IDC_CHECK1                      1054
#define IDC_RADIO15                     1054
#define IDC_RADIO_ENTITY                1054
#define IDC_RADIO_MODE_DEBUG            1054
#define IDC_RADIO_STATE_ACTIVE          1054
#define IDC_RADIO_WEATHER_USELAST       1054
#define IDC_CHECK2                      1055
#define IDC_CHECK_ENABLE_WHITECAPS      1055
#define IDC_CHECK_ENABLE_X              1055
#define IDC_CHECK_RESET_FLASH           1055
#define IDC_CHECK_SENSOR_ON_OFF         1055
#define IDC_CHECK_SUN_ENABLE            1055
#define IDC_CHECK_SYMBOL_TEXT_DEF       1055
#define IDC_CHECK_TIMESTAMP_VALID       1055
#define IDC_RADIO16                     1055
#define IDC_RADIO_PLUNGING              1055
#define IDC_RADIO_STATE_DESTROYED       1055
#define IDC_RADIO_WEATHER_MERGE         1055
#define IDC_CHECK3                      1056
#define IDC_CHECK_COLLISION_DETECT      1056
#define IDC_CHECK_DROPOUT               1056
#define IDC_CHECK_ENABLE_Y              1056
#define IDC_CHECK_MOON_ENABLE           1056
#define IDC_RADIO_AEROSOL_USELAST       1056
#define IDC_RADIO_ALIGN4                1056
#define IDC_RADIO_SPILLING              1056
#define IDC_CHECK_SMOOTHING_ENABLE      1056
#define IDC_CHECK_ENTITY_SUBSTITUTION_ENABLE 1057
#define IDC_CHECK4                      1057
#define IDC_CHECK_AUTO_GAIN             1057
#define IDC_CHECK_ENABLE_Z              1057
#define IDC_CHECK_INHERIT_ALPHA         1057
#define IDC_CHECK_STARFIELD_ENABLE      1057
#define IDC_RADIO_AEROSOL_MERGE         1057
#define IDC_RADIO_ALIGN5                1057
#define IDC_RADIO_SURGING               1057
#define IDC_CHECK_ARTPART_ROLL          1058
#define IDC_CHECK_ENABLE_YAW            1058
#define IDC_RADIO3                      1058
#define IDC_RADIO_ALIGN6                1058
#define IDC_RADIO_CLAMP_NONE            1058
#define IDC_RADIO_CLASS_VIEW            1058
#define IDC_RADIO_REGION_STATE_DESTROYED 1058
#define IDC_RADIO_TYPE_EXT              1058
#define IDC_RADIO_WEATHER_COND          1058
#define IDC_CHECK_INHERIT_ALPHA2        1058
#define IDC_CHECK_INHERIT_SMOOTHING_ENABLE2 1058
#define IDC_CHECK_ARTPART_PITCH         1059
#define IDC_CHECK_ENABLE_PITCH          1059
#define IDC_RADIO4                      1059
#define IDC_RADIO_AEROSOL_CONC          1059
#define IDC_RADIO_ALIGN7                1059
#define IDC_RADIO_CLAMP_NONCONFORMAL    1059
#define IDC_RADIO_CLASS_VIEWGROUP       1059
#define IDC_RADIO_CS_GEODETIC           1059
#define IDC_RADIO_MARITIME_USELAST      1059
#define IDC_CHECK_ARTPART_YAW           1060
#define IDC_CHECK_ENABLE_ROLL           1060
#define IDC_RADIO5                      1060
#define IDC_RADIO_ALIGN8                1060
#define IDC_RADIO_CLAMP_CONFORMAL       1060
#define IDC_RADIO_CLASS_TRACKER         1060
#define IDC_RADIO_CS_ENTITY             1060
#define IDC_RADIO_MARITIME_MERGE        1060
#define IDC_RADIO6                      1061
#define IDC_RADIO_MODE_ONESHOT          1061
#define IDC_RADIO_ORIENT1               1061
#define IDC_RADIO_TERRESTRIAL_USELAST   1061
#define IDC_RADIO7                      1062
#define IDC_RADIO_MODE_CONTINUOUS       1062
#define IDC_RADIO_ORIENT2               1062
#define IDC_RADIO_TERRESTRIAL_MERGE     1062
#define IDC_RADIO8                      1063
#define IDC_RADIO_ANIM_STATE_STOP       1063
#define IDC_RADIO_COORDSYSTEM_GEODETIC  1063
#define IDC_RADIO_ORIENT3               1063
#define IDC_SLIDER_ROLL                 1063
#define IDC_RADIO9                      1064
#define IDC_RADIO_ANIM_STATE_PAUSE      1064
#define IDC_RADIO_COORDSYSTEM_PARENT    1064
#define IDC_SLIDER_PITCH                1064
#define IDC_RADIO10                     1065
#define IDC_RADIO_ANIM_STATE_PLAY       1065
#define IDC_RADIO_COORDSYSTEM_SUBMODEL  1065
#define IDC_SLIDER_THROTTLE             1065
#define IDC_HTRIM                       1066
#define IDC_RADIO11                     1066
#define IDC_RADIO_ANIM_STATE_CONTINUE   1066
#define IDC_RADIO12                     1067
#define IDC_VTRIM                       1067
#define IDC_PITCH                       1068
#define IDC_RADIO13                     1068
#define IDC_BUTTON_FREEZE_RESUME        1069
#define IDC_RADIO14                     1069
#define IDC_EDIT9                       1070
#define IDC_SLIDER_PITCH2               1070
#define IDC_EDIT20                      1071
#define IDC_SPIN1                       1071
#define IDC_EDIT14                      1072
#define IDC_EDIT21                      1072
#define IDC_EDIT_BASE_ELEV              1072
#define IDC_EDIT_SCALE_U                1072
#define IDC_LONGITUDE                   1072
#define IDC_SPIN_ARTPART_Y              1072
#define IDC_ALTITUDE                    1073
#define IDC_EDIT15                      1073
#define IDC_EDIT22                      1073
#define IDC_EDIT_THICKNESS              1073
#define IDC_SPIN_ARTPART_Z              1073
#define IDC_AIRSPEED                    1074
#define IDC_EDIT16                      1074
#define IDC_EDIT_ID                     1074
#define IDC_SPIN_ARTPART_ROLL           1074
#define IDC_EDIT17                      1075
#define IDC_SPIN_ARTPART_PITCH          1075
#define IDC_EDIT18                      1076
#define IDC_LATITUDE                    1076
#define IDC_LIST_TYPES                  1076
#define IDC_SPIN_ARTPART_YAW            1076
#define IDC_EDIT19                      1077
#define IDC_HEADING                     1077
#define IDC_IPADDRESS_IG                1077
#define IDC_EDIT_IG_RCV_PORT            1078
#define IDC_ROLL                        1078
#define IDC_EDIT_LOCAL_RCV_PORT         1079
#define IDC_JOYBALL                     1079
#define IDC_CHECK_ASYNCHRONOUS          1080
#define IDC_COMBO_MODE                  1080
#define IDC_BUTTON_RESET                1081
#define IDC_EDIT_FRAME_RATE             1081
#define IDC_LABEL_FRAME_RATE            1082
#define IDC_LABEL_HZ                    1083
#define IDC_LIST_ENTITY_COMPONENTS      1084
#define IDC_LIST_ENTITY_COMP_STATES     1085
#define IDC_BUTTON_APPLY_COMP           1087
#define IDC_COMBO_ENTITY_COMP1          1089
#define IDC_COMBO_ENTITY_COMP2          1090
#define IDC_COMBO_ENTITY_COMP3          1091
#define IDC_COMBO_ENTITY_COMP4          1092
#define IDC_COMBO_ENTITY_COMP5          1093
#define IDC_COMBO_ENTITY_COMP6          1094
#define IDC_CHECK_ENTITY_COMP_AUTOAPPLY 1095
#define IDC_LIST_ENTITY_ARTPARTS        1096
#define IDC_CHECK_ENTITY_ARTPART_AUTOAPPLY 1097
#define IDC_CHECK_ARTPART_ENABLE        1098
#define IDC_CHECK_ARTPART_X             1099
#define IDC_CHECK_ARTPART_Y             1100
#define IDC_CHECK_ARTPART_Z             1101
#define IDC_EDIT_ARTPART_X              1102
#define IDC_EDIT_ARTPART_Y              1103
#define IDC_EDIT_ARTPART_Z              1104
#define IDC_EDIT_ARTPART_ROLL           1105
#define IDC_EDIT_ARTPART_PITCH          1106
#define IDC_EDIT_ARTPART_YAW            1107
#define IDC_SPIN_ARTPART_X              1108
#define IDC_COMBO_HAT_ID_RANGE          1109
#define IDC_BUTTON_APPLY_HAT            1110
#define IDC_BUTTON_ADD_HAT              1111
#define IDC_BUTTON_REMOVE_HAT           1112
#define IDC_CHECK_CONTINUOUS            1113
#define IDC_EDIT_HAT_X                  1117
#define IDC_EDIT_HAT_Y                  1118
#define IDC_EDIT_HAT_Z                  1119
#define IDC_CHECK_HAT_VALID             1120
#define IDC_EDIT_CAMERA_ROLL            1124
#define IDC_CHECK_REQUEST_HAT           1125
#define IDC_EDIT_CAMERA_PITCH           1125
#define IDC_EDIT_LOS_DEST_X_MIN_RANGE   1125
#define IDC_CHECK_REQUEST_HOT           1126
#define IDC_EDIT_CAMERA_HEADING         1126
#define IDC_EDIT_LOS_DEST_Y_MAX_RANGE   1126
#define IDC_COMBO_LOS_ID_RANGE          1128
#define IDC_BUTTON_ADD_LOS              1129
#define IDC_BUTTON_REMOVE_LOS           1130
#define IDC_CHECK_EXT_RESPONSE          1131
#define IDC_EDIT_LOS_AZ                 1132
#define IDC_EDIT_LOS_EL                 1133
#define IDC_EDIT_LOS_MAT_MASK           1134
#define IDC_COMBO_ENTITY                1135
#define IDC_EDIT_LOS_ALPHA_THRESH       1135
#define IDC_EDIT_LOS_SOURCE_X           1136
#define IDC_EDIT_LOS_DEST_Z             1137
#define IDC_EDIT_VIEW_ID                1137
#define IDC_EDIT_LOS_SOURCE_Y           1138
#define IDC_COMBO_VIEW_TYPE             1139
#define IDC_EDIT_LOS_SOURCE_Z           1139
#define IDC_COMBO_VIEW_GROUP            1140
#define IDC_EDIT_RIGHT_FOV              1141
#define IDC_BUTTON_APPLY_LOS            1142
#define IDC_EDIT_TOP_FOV                1142
#define IDC_EDIT_LEFT_FOV               1143
#define IDC_RADIO_LOS_TYPE_SEGMENT      1143
#define IDC_EDIT_BOTTOM_FOV             1144
#define IDC_RADIO_LOS_TYPE_VECTOR       1144
#define IDC_CHECK_LOS_REQ_GDC           1145
#define IDC_EDIT_NEAR_FOV               1145
#define IDC_CHECK_LOS_DEST_GDC          1146
#define IDC_EDIT_FAR_FOV                1146
#define IDC_LABEL_DESTINATION           1147
#define IDC_RADIO_PIXELREP_NONE         1147
#define IDC_RADIO_PIXELREP_1_2          1148
#define IDC_RADIO_PIXELREP_2_1          1149
#define IDC_RADIO_PIXELREP_2_2          1150
#define IDC_RADIO_MIRROR_NONE           1151
#define IDC_CHECK_LOS_VALID             1152
#define IDC_RADIO_MIRROR_HORZ           1152
#define IDC_RADIO_MIRROR_VERT           1153
#define IDC_STATIC_RESP_ENTITY_ID       1153
#define IDC_RADIO_MIRROR_BOTH           1154
#define IDC_RADIO_MIRROR_HORZ_VERT      1154
#define IDC_STATIC_RESP_LATITUDE        1154
#define IDC_STATIC_RESP_LONGITUDE       1155
#define IDC_EDIT_VIEWPOS_Z              1156
#define IDC_RADIO_PIXELREP_1X2          1156
#define IDC_STATIC_RESP_ALTITUDE        1156
#define IDC_RADIO_PIXELREP_2X1          1157
#define IDC_STATIC_RESP_RANGE           1157
#define IDC_LABEL_RESP_ENTITY_ID        1158
#define IDC_RADIO_PIXELREP_2X2          1158
#define IDC_LABEL_RESP_LATITUDE         1159
#define IDC_RADIO_PROJECTION_PERSPECTIVE 1159
#define IDC_LABEL_RESP_LONGITUDE        1160
#define IDC_RADIO_PERSPECTIVE_ORTHO     1160
#define IDC_LABEL_RESP_ALTITUDE         1161
#define IDC_LABEL_RESP_RANGE            1162
#define IDC_LABEL_RESP_LATITUDE_UNITS   1163
#define IDC_LABEL_RESP_LONGITUDE_UNITS  1164
#define IDC_LABEL_RESP_ALTITUDE_UNITS   1165
#define IDC_LABEL_RESP_RANGE_UNITS      1166
#define IDC_STATIC_RESP_AZIMUTH         1167
#define IDC_STATIC_RESP_ELEVATION       1168
#define IDC_STATIC_RESP_MATERIAL_CODE   1169
#define IDC_STATIC_RESP_COLOR           1170
#define IDC_LABEL_RESPONSE_COUNT        1171
#define IDC_STATIC_RESP_HAT             1171
#define IDC_BUTTON_APPLY_COLL           1172
#define IDC_STATIC_RESP_HOT             1172
#define IDC_BUTTON_APPLY_ARTPART        1173
#define IDC_STATIC_RESP_MATERIAL        1173
#define IDC_LABEL_DEST_LAT_OR_MIN_RANGE 1174
#define IDC_LABEL_DEST_LON_OR_MAX_RANGE 1175
#define IDC_LABEL_DEST_ALT              1176
#define IDC_LABEL_REQ_AZ                1177
#define IDC_COMBO_FLY_WEAPON            1178
#define IDC_LABEL_REQ_EL                1178
#define IDC_COMBO_COLLISION_ID          1179
#define IDC_COMBO_FLY_TARGET            1179
#define IDC_BUTTON_ADD_SEGMENT          1180
#define IDC_BUTTON_REMOVE_COLL          1181
#define IDC_CHECK_COLL_ENABLE           1182
#define IDC_BUTTON_ADD_VOLUME           1183
#define IDC_CHECK_SEG_OR_VOL_ENABLE     1184
#define IDC_GROUPBOX_SEGMENT            1186
#define IDC_LABEL_START_OR_TYPE         1187
#define IDC_LABEL_END                   1188
#define IDC_LABEL_X_HEIGHT_RADIUS       1189
#define IDC_BUTTON_ARTPARTS_APPLY       1190
#define IDC_LABEL_Y_WIDTH               1190
#define IDC_BUTTON_ARTPARTS_UNDO        1191
#define IDC_LABEL_Z_DEPTH               1191
#define IDC_LABEL_MASK                  1192
#define IDC_LABEL_Y_WIDTH_UNITS         1193
#define IDC_LABEL_Z_DEPTH_UNITS         1194
#define IDC_LABEL_YAW                   1195
#define IDC_LABEL_PITCH                 1196
#define IDC_LABEL_ROLL                  1197
#define IDC_EDIT_MASK                   1198
#define IDC_CHECK_ARTPARTS_ACTIVE       1199
#define IDC_EDIT_NOTIFICATION           1199
#define IDC_LABEL_YAW_UNITS             1200
#define IDC_LABEL_PITCH_UNITS           1201
#define IDC_LABEL_ROLL_UNITS            1202
#define IDC_RADIO_SPHERE                1203
#define IDC_RADIO_CUBOID                1204
#define IDC_EDIT_X1                     1205
#define IDC_EDIT_Y1                     1206
#define IDC_EDIT_Z1                     1207
#define IDC_EDIT_X2                     1208
#define IDC_EDIT_X2_HEIGHT_RADIUS       1208
#define IDC_EDIT_Y2                     1209
#define IDC_EDIT_Y2_WIDTH               1209
#define IDC_EDIT_Z2                     1210
#define IDC_EDIT_Z2_DEPTH               1210
#define IDC_EDIT_YAW                    1211
#define IDC_EDIT_PITCH                  1212
#define IDC_EDIT_ROLL                   1213
#define IDC_LABEL_X1                    1214
#define IDC_LABEL_Y1                    1215
#define IDC_SPIN_ARTPARTS_X             1215
#define IDC_LABEL_Z1                    1216
#define IDC_SPIN_ARTPARTS_H             1216
#define IDC_BUTTON_SELECT_ALL           1217
#define IDC_BUTTON_SELECT_NONE          1218
#define IDC_CHECK_ARTPARTS_AUTOAPPLY    1218
#define IDC_CHECK_HATHOT                1219
#define IDC_EDIT_ARTPARTS_X             1219
#define IDC_CHECK_HATHOT_EXT            1220
#define IDC_EDIT_ARTPARTS_Y             1220
#define IDC_CHECK_LOS                   1221
#define IDC_EDIT_ARTPARTS_Z             1221
#define IDC_CHECK_LOS_EXT               1222
#define IDC_EDIT_ARTPARTS_YAW           1222
#define IDC_CHECK_SENSOR                1223
#define IDC_EDIT_ARTPARTS_PITCH         1223
#define IDC_CHECK_SENSOR_EXT            1224
#define IDC_EDIT_ARTPARTS_ROLL          1224
#define IDC_CHECK_POSITION              1225
#define IDC_CHECK_WEATHER               1226
#define IDC_CHECK_AEROSOL               1227
#define IDC_CHECK_ENV_REGION_CONTROL    1228
#define IDC_CHECK_TERRESTRIAL           1229
#define IDC_CHECK_CD_SEGMENT            1230
#define IDC_CHECK_CD_VOLUME             1231
#define IDC_CHECK_ANIMATION             1232
#define IDC_CHECK_EVENT                 1233
#define IDC_CHECK_IG_MESSAGE            1234
#define IDC_CHECK_IG_CONTROL            1235
#define IDC_CHECK_SOF                   1236
#define IDC_CHECK_ENTITY_CONTROL        1237
#define IDC_CHECK_CC_ENTITY_CONTROL     1238
#define IDC_CHECK_COMPONENT_CONTROL     1239
#define IDC_CHECK_SHORT_COMPONENT_CONTROL 1240
#define IDC_CHECK_ARTPART_CONTROL       1241
#define IDC_CHECK_SHORT_ARTPART_CONTROL 1242
#define IDC_CHECK_RATE_CONTROL          1243
#define IDC_CHECK_MARITIME              1244
#define IDC_CHECK_CELESTIAL_CONTROL     1245
#define IDC_CHECK_ATMOSPHERE_CONTROL    1246
#define IDC_CHECK_WEATHER_CONTROL       1247
#define IDC_CHECK_MARITIME_CONTROL      1248
#define IDC_CHECK_WAVE_CONTROL          1249
#define IDC_CHECK_TERRESTRIAL_CONTROL   1250
#define IDC_CHECK_VIEW_CONTROL          1251
#define IDC_CHECK_SENSOR_CONTROL        1252
#define IDC_CHECK_TRACKER               1253
#define IDC_CHECK_ERM_DEF               1254
#define IDC_CHECK_TRAJECTORY_DEF        1255
#define IDC_CHECK_VIEW_DEF              1256
#define IDC_CHECK_CD_SEGMENT_DEF        1257
#define IDC_CHECK_CD_VOLUME_DEF         1258
#define IDC_CHECK_HATHOT_REQUEST        1259
#define IDC_CHECK_LOS_SEGMENT_REQUEST   1260
#define IDC_CHECK_LOS_VECTOR_REQUEST    1261
#define IDC_CHECK_POSITION_REQUEST      1262
#define IDC_CHECK_ENV_CONDITIONS_REQUEST 1263
#define IDC_BUTTON_REORDER_TO_TOP       1264
#define IDC_RADIO_PERSPECTIVE           1265
#define IDC_RADIO_ORTHOGRAPHIC          1266
#define IDC_BUTTON_SLEW                 1267
#define IDC_EDIT_VIEW_TYPE              1272
#define IDC_DATE                        1277
#define IDC_TIME                        1278
#define IDC_EDIT_INTENSITY              1279
#define IDC_EDIT_GLOBAL_HUMIDITY        1280
#define IDC_CHECK_ENABLE_ATMOSPHERICS   1281
#define IDC_COMBO_DATABASE              1282
#define IDC_EDIT_GLOBAL_BARO_PRESSURE   1282
#define IDC_EDIT_GLOBAL_VISIBILITY      1283
#define IDC_EDIT_GLOBAL_WIND_DIR        1284
#define IDC_EDIT_GLOBAL_WIND_VERT       1285
#define IDC_EDIT_GLOBAL_WIND_HORZ       1286
#define IDC_EDIT_GLOBAL_TEMP            1288
#define IDC_LABEL_ERM                   1289
#define IDC_LABEL_LATITUDE              1290
#define IDC_LABEL_LONGITUDE             1291
#define IDC_LABEL_ALTITUDE              1292
#define IDC_LABEL_RADIUS                1293
#define IDC_LABEL_FLATTENING            1294
#define IDC_CHECK_ENABLE_WEATHER        1297
#define IDC_SPIN_SEVERITY               1298
#define IDC_EDIT_TEMPERATURE            1299
#define IDC_EDIT_COVERAGE               1300
#define IDC_EDIT_HUMIDITY               1302
#define IDC_PICTURE                     1302
#define IDC_PICTURE_PERSPECTIVE         1302
#define IDC_EDIT_BARO_PRESSURE          1303
#define IDC_PICTURE_ORTHO               1303
#define IDC_CHECK_ENABLE_WINDS          1305
#define IDC_CHECK_ENABLE_LIGHTNING      1306
#define IDC_EDIT_SEVERITY               1307
#define IDC_EDIT_AEROSOL                1308
#define IDC_CHECK_ENABLE_BOTTOM_SCUD    1309
#define IDC_EDIT_HORZ_WINDSPEED         1310
#define IDC_EDIT_VERT_WINDSPEED         1311
#define IDC_EDIT_WIND_DIRECTION         1312
#define IDC_COMBOBOXEX_CLOUD_TYPE       1314
#define IDC_BUTTON_APPLY                1315
#define IDC_EDIT_VISIBILITY             1316
#define IDC_EDIT_LAYER_ID               1317
#define IDC_COMBO_FILENAME              1318
#define IDC_PROGRESS_METER              1324
#define IDC_LABEL_TIME                  1325
#define IDC_LABEL_END_TIME              1326
#define IDC_BUTTON_BROWSE               1327
#define IDC_BUTTON_RECORD               1328
#define IDC_BUTTON_PLAY                 1329
#define IDC_BUTTON_PAUSE                1330
#define IDC_BUTTON_LOOP                 1332
#define IDC_LABEL_PROGRESS              1332
#define IDC_BUTTON_STOP                 1333
#define IDC_BUTTON_EDIT                 1334
#define IDC_LABEL_WAIT                  1335
#define IDC_LABEL_WAITTIME              1336
#define IDC_EDIT_VERSION                1337
#define IDC_EDIT_FRAME_COUNTER          1338
#define IDC_EDIT_BYTESWAP               1339
#define IDC_EDIT_TIMESTAMP              1340
#define IDC_EDIT_ALPHA                  1344
#define IDC_CHECK_ANIM_LOOP             1345
#define IDC_LABEL_LATX                  1346
#define IDC_EDIT_SPEED                  1346
#define IDC_LABEL_LONY                  1347
#define IDC_LABEL_ALTZ                  1348
#define IDC_LABEL_UNITS_X               1349
#define IDC_LABEL_LATX2                 1349
#define IDC_LABEL_COUNTRY               1349
#define IDC_LABEL_UNITS_Y               1350
#define IDC_LABEL_UNITS_Z               1351
#define IDC_EDIT_LATX                   1352
#define IDC_EDIT_LONY                   1353
#define IDC_EDIT_ALTZ                   1354
#define IDC_COMBOBOXEX_ENTITY_ID        1356
#define IDC_COMBOBOXEX_PART_ID          1357
#define IDC_EDIT_LAT                    1357
#define IDC_COMBOBOXEX_ANIMATION_ID     1357
#define IDC_COMBOBOXEX_GROUP_ID         1358
#define IDC_EDIT_LON                    1358
#define IDC_EDIT_INSTANCE_ID            1359
#define IDC_EDIT_COMPONENT_ID           1360
#define IDC_COMBOBOXEX_PARENT_ID        1361
#define IDC_EDIT_COMPONENT_STATE        1361
#define IDC_COMBOBOXEX_COMPONENT_CLASS  1368
#define IDC_EDIT_DATA1                  1372
#define IDC_CHECK_ENABLE_ARTPART        1373
#define IDC_EDIT_X                      1374
#define IDC_EDIT_Y                      1375
#define IDC_EDIT_Z                      1376
#define IDC_CHECK_ENABLE_ARTPART1       1377
#define IDC_EDIT_DATA2                  1377
#define IDC_COMBOBOXEX_PART_ID1         1378
#define IDC_EDIT_DATA3                  1378
#define IDC_EDIT_DATA4                  1379
#define IDC_EDIT_VALUE1                 1379
#define IDC_EDIT_DATA5                  1380
#define IDC_COMBOBOXEX_PART_ID2         1381
#define IDC_EDIT_DATA6                  1381
#define IDC_CHECK_ENABLE_ARTPART2       1382
#define IDC_EDIT_VALUE2                 1383
#define IDC_COMBOBOXEX_DOF1             1385
#define IDC_COMBOBOXEX_DOF2             1386
#define IDC_EDIT_HOUR                   1386
#define IDC_EDIT_MINUTE                 1387
#define IDC_CHECK_EPHEMERIS_ENABLE      1388
#define IDC_CHECK_DATETIME_VALID        1389
#define IDC_EDIT_AIR_TEMP               1389
#define IDC_EDIT_MONTH                  1390
#define IDC_EDIT_VISIBILITY_RANGE       1390
#define IDC_EDIT_DAY                    1391
#define IDC_EDIT_WIND_SPEED_HORZ        1391
#define IDC_EDIT_WIND_SPEED_VERT        1392
#define IDC_EDIT_YEAR                   1392
#define IDC_CHECK_ATMOSPHERICS_ENABLE   1393
#define IDC_EDIT_SECONDS                1393
#define IDC_EDIT_REGION_ID              1394
#define IDC_RADIO_REGION_STATE_INACTIVE 1395
#define IDC_EDIT_LATITUDE               1396
#define IDC_EDIT_LONGITUDE              1397
#define IDC_EDIT_ROTATION               1398
#define IDC_EDIT_SIZE_X                 1399
#define IDC_EDIT_SIZE_Y                 1400
#define IDC_EDIT_RADIUS                 1401
#define IDC_COMBOBOXEX_REGION_ENTITY_ID 1402
#define IDC_LABEL_REGION_ENTITY_ID      1403
#define IDC_COMBOBOXEX_LAYER_ID         1404
#define IDC_CHECK_ENABLE_CONDITIONS     1405
#define IDC_EDIT_SURFACE_HEIGHT         1406
#define IDC_EDIT_WATER_TEMP             1407
#define IDC_EDIT_CLARITY                1408
#define IDC_EDIT_COND_ID                1409
#define IDC_CHECK_ENABLE_WAVE           1410
#define IDC_EDIT_WAVE_ID                1411
#define IDC_EDIT_HEIGHT                 1412
#define IDC_EDIT_WAVELENGTH             1413
#define IDC_EDIT_PERIOD                 1414
#define IDC_EDIT_DIRECTION              1415
#define IDC_EDIT_PHASE_OFFSET           1416
#define IDC_EDIT_LEADING                1417
#define IDC_COMBOBOXEX_VIEW_ID          1418
#define IDC_RADIO_POLARITY_WHITE        1420
#define IDC_RADIO_POLARITY_BLACK        1421
#define IDC_COMBOBOXEX_TRACK_MODE       1422
#define IDC_RADIO_TRACK_WHITE           1423
#define IDC_RADIO_TRACK_BLACK           1424
#define IDC_RADIO_RESPONSE_NORMAL       1425
#define IDC_RADIO_RESPONSE_EXTENDED     1426
#define IDC_EDIT_GAIN                   1427
#define IDC_EDIT_LEVEL                  1428
#define IDC_EDIT_AC_COUPLING            1429
#define IDC_EDIT_NOISE                  1430
#define IDC_EDIT_SENSOR_ID              1431
#define IDC_RADIO_ATTACH_TO_VIEW        1433
#define IDC_RADIO_ATTACH_TO_GROUP       1434
#define IDC_CHECK_TRACKER_ENABLE        1435
#define IDC_CHECK_BORESIGHT_ENABLE      1436
#define IDC_CHECK_X_ENABLE              1437
#define IDC_CHECK_YAW_ENABLE            1438
#define IDC_CHECK_Y_ENABLE              1439
#define IDC_CHECK_PITCH_ENABLE          1440
#define IDC_LABEL_AIRSPEED              1440
#define IDC_CHECK_Z_ENABLE              1441
#define IDC_LABEL_KNOTS                 1441
#define IDC_CHECK_ROLL_ENABLE           1442
#define IDC_LABEL_VIEW_OR_GROUP         1443
#define IDC_EDIT_TRACKER_ID             1444
#define IDC_CHECK_ENABLE                1445
#define IDC_EDIT_FLATTENING             1446
#define IDC_EDIT_PITCH_ACCEL            1448
#define IDC_EDIT_ROLL_ACCEL             1449
#define IDC_EDIT_TOP                    1450
#define IDC_CHECK_ENABLE_TOP            1451
#define IDC_EDIT_BOTTOM                 1452
#define IDC_CHECK_ENABLE_BOTTOM         1453
#define IDC_EDIT_LEFT                   1454
#define IDC_CHECK_ENABLE_LEFT           1455
#define IDC_EDIT_RIGHT                  1456
#define IDC_CHECK_ENABLE_RIGHT          1457
#define IDC_EDIT_NEAR                   1458
#define IDC_CHECK_ENABLE_NEAR           1459
#define IDC_EDIT_FAR                    1460
#define IDC_CHECK_ENABLE_FAR            1461
#define IDC_CHECK_REORDER               1462
#define IDC_CHECK_ENABLE_SEGMENT        1464
#define IDC_EDIT_SEGMENT_ID             1466
#define IDC_EDIT_VOLUME_ID              1467
#define IDC_CHECK_ENABLE_VOLUME         1468
#define IDC_LABEL_HEIGHT_RADIUS         1469
#define IDC_EDIT_HEIGHT_RADIUS          1470
#define IDC_EDIT_WIDTH                  1471
#define IDC_EDIT_DEPTH                  1472
#define IDC_EDIT_MATERIAL_MASK          1473
#define IDC_EDIT_LAT_X                  1474
#define IDC_EDIT_LON_Y                  1475
#define IDC_EDIT_ALT_Z                  1476
#define IDC_LABEL_LAT_X                 1477
#define IDC_LABEL_LON_Y                 1478
#define IDC_LABEL_ALT_Z                 1479
#define IDC_LABEL_LAT_X_UNITS           1480
#define IDC_LABEL_LON_Y_UNITS           1481
#define IDC_EDIT_HAT_ID                 1482
#define IDC_RADIO_RESP_GEODETIC         1483
#define IDC_RADIO_RESP_ENTITY           1484
#define IDC_RADIO_SRC_GEODETIC          1485
#define IDC_RADIO_SRC_ENTITY            1486
#define IDC_EDIT_DEST_LAT_X             1487
#define IDC_EDIT_DEST_LON_Y             1488
#define IDC_EDIT_DEST_ALT_Z             1489
#define IDC_LABEL_DEST_LAT_X            1490
#define IDC_LABEL_DEST_LON_Y            1491
#define IDC_LABEL_DEST_ALT_Z            1492
#define IDC_LABEL_DEST_LAT_X_UNITS      1493
#define IDC_LABEL_DEST_LON_Y_UNITS      1494
#define IDC_RADIO_DEST_GEODETIC         1495
#define IDC_RADIO_DEST_ENTITY           1496
#define IDC_EDIT_LOS_ID                 1497
#define IDC_RADIO_TYPE_BASIC            1498
#define IDC_EDIT_SRC_LAT_X              1499
#define IDC_EDIT_SRC_LON_Y              1500
#define IDC_EDIT_SRC_ALT_Z              1501
#define IDC_LABEL_SRC_LAT_X_UNITS       1502
#define IDC_LABEL_SRC_LON_Y_UNITS       1503
#define IDC_LABEL_SRC_ALT_Z             1504
#define IDC_LABEL_SRC_LON_Y             1505
#define IDC_LABEL_SRC_LAT_X             1506
#define IDC_EDIT_ALPHA_THRESHOLD        1507
#define IDC_EDIT_AZIMUTH                1508
#define IDC_EDIT_ELEVATION              1509
#define IDC_EDIT_MIN_RANGE              1510
#define IDC_EDIT_MAX_RANGE              1511
#define IDC_LABEL_OBJECT_ID             1512
#define IDC_COMBOBOXEX_OBJECT_ID        1513
#define IDC_EDIT_REQUEST_ID             1514
#define IDC_EDIT_ALTITUDE               1515
#define IDC_CHECK_BIG_ENDIAN            1516
#define IDC_COMBOBOXEX_TARGET           1517
#define IDC_LIST_TERMINATING            1518
#define IDC_CHECK_PRECISION_10          1519
#define IDC_LIST_PERSISTENT             1519
#define IDC_CHECK_PRECISION_50          1520
#define IDC_LIST_DETONATING             1520
#define IDC_CHECK_PRECISION_100         1521
#define IDC_EDIT_DEFAULT_DB             1522
#define IDC_LABEL_FLYMODE               1523
#define IDC_COMBO1                      1524
#define IDC_COMBO2                      1525
#define IDC_COMBO_VERSION               1525
#define IDC_EDIT_UPDATE_PERIOD          1526
#define IDC_EDIT_DEST_ENTITY_ID         1527
#define IDC_CHECK_DEST_VALID            1528
#define IDC_LABEL_X_LEFT                1529
#define IDC_LABEL_Y_RIGHT               1530
#define IDC_LABEL_Z_TOP                 1531
#define IDC_LABEL_YAW_BOTTOM            1532
#define IDC_GRAPH                       1533
#define IDC__LABEL_ORIENTATION          1533
#define IDC_CHECK_PUBLISH_SELECTED_ENTITY 1622
#define IDC_EDIT_SELECTED_ENTITY_VIEW_ID 1623
#define IDC_LABEL_WIDTH                 1534
#define IDC_MAX_PERIOD                  1534
#define IDC_LABEL_HEIGHT                1535
#define IDC_MIN_PERIOD                  1535
#define IDC_MEDIAN                      1536
#define IDC_RADIO_ALIGN0                1536
#define IDC_RADIO_ALIGN1                1537
#define IDC_WIDTH_REFERENCE             1537
#define IDC_RADIO_ALIGN2                1538
#define IDC_RADIO_ALIGN3                1539
#define IDC_RADIO_ORIENT0               1540
#define IDC_PACKET_SIZE                 1541
#define IDC_EDIT_SYMBOL_ID              1542
#define IDC_SCROLLBAR1                  1542
#define IDC_EDIT_FONT_ID                1543
#define IDC_EDIT_FONT_SIZE              1544
#define IDC_EDIT_STRING                 1545
#define IDC_RADIO_LINE                  1546
#define IDC_RADIO_FILLED                1547
#define IDC_EDIT_LINE_WIDTH             1548
#define IDC_LABEL_THROTTLE_TOP          1548
#define IDC_EDIT_STIPPLE_PATTERN        1549
#define IDC_LABEL_THROTTLE_MIDDLE       1549
#define IDC_CLAMP                       1549
#define IDC_EDIT_STIPPLE_LENGTH         1550
#define IDC_LABEL_THROTTLE_BOTTOM       1550
#define IDC_CLAMP2                      1550
#define IDC_COMBO3                      1554
#define IDC_COMBO4                      1555
#define IDC_COMBO5                      1556
#define IDC_COMBO6                      1557
#define IDC_BUTTON1                     1573
#define IDC_BUTTON2                     1574
#define IDC_GRID                        1575
#define IDC_COMBO_PRIMITIVE             1576
#define IDC_EDIT_SURFACE_ID             1577
#define IDC_EDIT_LAYER                  1578
#define IDC_CHECK_ATTACH                1579
#define IDC_EDIT_PARENT                 1580
#define IDC_EDIT_FLASH_PERIOD           1581
#define IDC_EDIT_FLASH_DUTY_CYCLE       1582
#define IDC_EDIT_RED                    1583
#define IDC_EDIT_GREEN                  1584
#define IDC_EDIT_BLUE                   1585
#define IDC_CHECK_INHERIT_COLOR         1586
#define IDC_EDIT_POS_U                  1587
#define IDC_EDIT_POS_V                  1588
#define IDC_EDIT_SCALE_V                1589
#define IDC_EDIT_DATUM1                 1590
#define IDC_EDIT_DATUM2                 1591
#define IDC_CHECK_SYMBOL_CONTROL        1592
#define IDC_CHECK6                      1593
#define IDC_CHECK_SHORT_SYMBOL_CONTROL  1593
#define IDC_CHECK_SYMBOL_SURFACE_DEF    1594
#define IDC_CHECK_SYMBOL_CIRCLE_DEF     1595
#define IDC_CHECK_SYMBOL_LINE_DEF       1596
#define IDC_CHECK_SYMBOL_CLONE          1597
#define IDC_EDIT_BOTTOM_SCUD_FREQ       1597
#define IDC_CHECK_SYMBOL_CONTROL2       1598
#define IDC_EDIT_BOTTOM_TRANSITION_BAND 1598
#define IDC_EDIT_TOP_SCUD_FREQ          1599
#define IDC_EDIT_TOP_TRANSITION_BAND    1600
#define IDC_CHECK_ENABLE_TOP_SCUD       1601
#define IDC_EDIT_YAW_ACCEL              1602
#define IDC_CHECK_EXTENDED_ENTITY_TYPE2 1602
#define IDC_CHECK_EXTENDED_ENTITY_TYPE  1602
#define IDC_EDIT_ENTITY_KIND            1603
#define IDC_EDIT_ENTITY_DOMAIN          1604
#define IDC_EDIT_ENTITY_COUNTRY         1605
#define IDC_EDIT_ENTITY_CATEGORY        1606
#define IDC_EDIT_ENTITY_SUBCATEGORY     1607
#define IDC_EDIT_ENTITY_SPECIFIC        1608
#define IDC_EDIT_ENTITY_EXTRA           1609
#define IDC_EDIT_TEXTURE_ID             1610
#define IDC_EDIT_TEXTURE_ID2            1610
#define IDC_NEAREST                     1611
#define IDC_NEAREST2                    1612
#define IDC_REPEAT                      1613
#define IDC_LABEL_KIND                  1613
#define IDC_REPEAT2                     1614
#define IDC_COMBOBOXEX_DESTINATION_ID   1614
#define IDC_LABEL_CATEGORY              1614
#define IDC_LABEL_SPECIFIC              1615
#define IDC_LABEL_DOMAIN                1616
#define IDC_LABEL_SUBCATEGORY           1617
#define IDC_LABEL_EXTRA                 1618
#define IDC_COMBO_SETUP_PROFILE         1619
#define IDC_BUTTON_SAVE_SETUP_PROFILE   1620
#define IDC_BUTTON_DELETE_SETUP_PROFILE 1621
#define ID_CONFIGURATION                32771
#define ID_VIEW_CONFIGURATION           32772
#define ID_FILE_LOAD_TEMPLATE           32775
#define ID_FILE_SAVE_AS_DEFAULT         32776
#define ID_FILE_SAVE_TEMPLATE           32777
#define ID_VIEW_HIERARCHY               32778
#define ID_CONFIG_CLOSE                 32779
#define ID_CONFIG_ADD_ITEM              32780
#define ID_CONFIG_DELETE_ITEM           32781
#define ID_EXERCISE_RESET_HOST          32781
#define ID_VIEW_EXPAND_ALL              32792
#define ID_VIEW_COLLAPSE_ALL            32793
#define ID_VIEW_VIEWS                   32797
#define ID_DEBUG_CLEAR                  32800
#define ID_DEBUG_FILTER                 32801
#define ID_DEBUG_CAPTURE                32802
#define ID_EXERCISE_RESET_SCENARIO      32813
#define ID_EXERCISE_RUN                 32815
#define ID_EXERCISE_PAUSE               32816
#define ID_VIEW_TEST                    32817
#define ID_EXERCISE_RESET_IG            32819
#define ID_EXERCISE_RESET_ALL           32820
#define ID_VIEW_HISTORY                 32821
#define ID_ENTITY_ADD                   32830
#define ID_ENTITY_DELETE                32831
#define ID_VIEW_ENVIRONMENT             32832
#define ID_CONFIG_ADD_ITEM_ENTITY       32833
#define ID_CONFIG_ADD_ITEM_COMPONENT    32834
#define ID_CONFIG_ADD_ITEM_COMPSTATE    32835
#define ID_CONFIG_ADD_ITEM_ARTPART      32836
#define ID_CONFIG_ADD_ITEM_ATTACHPOINT  32837
#define ID_CONFIG_DELETE_ITEM_ENTITY    32838
#define ID_CONFIG_DELETE_ITEM_COMPONENT 32839
#define ID_CONFIG_DELETE_ITEM_COMPSTATE 32840
#define ID_CONFIG_DELETE_ITEM_ARTPART   32841
#define ID_CONFIG_DELETE_ITEM_ATTACHPOINT 32842
#define ID_TOOLS_RECORDPLAYBACK         32843
#define ID_TREE_ADD                     32844
#define ID_TREE_REMOVE                  32845
#define ID_TREE_EXPAND                  32846
#define ID_TREE_COLLAPSE                32847
#define ID_TREE_DETACH                  32848
#define ID_TOOLS_FLY                    32849
#define ID_FILE_SETUP                   32850
#define ID_VIEW_CLEAR_MESSAGES          32852
#define ID_FILE_LOAD_CONFIG             32853
#define ID_CONFIG_NOT_USED              32855
#define ID_WATCH_CAPTURE                32856
#define ID_WATCH_FILTER                 32857
#define ID_WATCH_CLEAR                  32858
#define ID_SEND_PACKET                  32859
#define ID_TOOLS_SCRIPT                 32860
#define ID_PACKET_IG_CONTROL            32863
#define ID_PACKET_ENTITY_POSITION       32864
#define ID_PACKET_CLAMPED_ENTITY_POSITION 32865
#define ID_PACKET_COMPONENT             32866
#define ID_PACKET_SHORT_COMPONENT       32867
#define ID_PACKET_ARTPART               32868
#define ID_PACKET_SHORT_ARTPART         32869
#define ID_PACKET_VELOCITY              32870
#define ID_PACKET_CELSPHERE             32871
#define ID_PACKET_ATMOSPHERE            32872
#define ID_PACKET_ENV_REGION            32873
#define ID_PACKET_WEATHER               32874
#define ID_PACKET_MARITIME              32875
#define ID_PACKET_WAVE                  32876
#define ID_PACKET_TERRESTRIAL           32877
#define ID_PACKET_VIEW_CONTROL          32878
#define ID_PACKET_SENSOR                32879
#define ID_PACKET_MOTION_TRACKER        32880
#define ID_PACKET_ERM                   32881
#define ID_PACKET_TRAJECTORY            32882
#define ID_PACKET_VIEW_DEF              32883
#define ID_PACKET_CD_SEGMENT            32884
#define ID_PACKET_CD_VOLUME             32885
#define ID_PACKET_HAT                   32886
#define ID_PACKET_LOS_SEGMENT           32887
#define ID_PACKET_LOS_VECTOR            32888
#define ID_PACKET_POSITION              32889
#define ID_PACKET_ENV_COND              32890
#define ID_ANIM_PLAY                    32892
#define ID_ANIM_PAUSE                   32893
#define ID_ANIM_STOP                    32894
#define ID_HELP_CONTENTS                32895
#define ID_PACKET_SYMBOLSURFACEDEFINITION 32902
#define ID_PACKET_SYMBOLTEXTDEFINITION  32903
#define ID_PACKET_SYMBOLPOLYGONDEFINITION 32904
#define ID_PACKET_SYMBOLCONTROL         32905
#define ID_PACKET_SHORTSYMBOLCONTROL    32906
#define ID_PACKET_SYMBOLCIRCLEDEFINITION 32908
#define ID_PACKET_SYMBOLCLONE           32910
#define ID_PACKET_ANIMATIONCONTROL      32911
#define ID_PACKET_ACCELERATION          32912
#define ID_PACKET_ENTITY                32913
#define ID_Menu                         32914
#define ID_Menu32914                    32914
#define ID_Menu32915                    32915
#define ID_PACKET_SYMBOLTEXTUREDCIRCLEDEFINITION 32916
#define ID_PACKET_SYMBOLTEXTUREDPOLYGONDEFINITION 32917
#define IDS_INDICATOR_FRAMERATE_OLD     59142
#define IDS_INDICATOR_IGMODE            59143
#define IDS_INDICATOR_FR_STATUS         59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32919
#define _APS_NEXT_CONTROL_VALUE         1624
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
