//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DummyIG4.rc
//
#define IDS_HELLO                       1
#define IDD_DIALOG_FILTER               101
#define IDC_BUTTON_CLEAR                1000
#define IDC_CHECK_ENTITY_CONTROL        1001
#define IDC_CHECK_COMPONENT_CONTROL     1002
#define IDC_CHECK_ART_PART_CONTROL      1003
#define IDC_CHECK_RATE_CONTROL          1004
#define IDC_CHECK_ENV_REGION_CONTROL    1005
#define IDC_CHECK_WEATHER_CONTROL       1006
#define IDC_CHECK_VIEW_CONTROL          1007
#define IDC_CHECK_SENSOR_CONTROL        1008
#define IDC_CHECK_TRAJ_DEF              1009
#define IDC_CHECK_VIEW_DEF              1011
#define IDC_CHECK_COLL_SEG_DEF          1012
#define IDC_CHECK_COLL_VOL_DEF          1013
#define IDC_CHECK_HAT_REQUEST           1014
#define IDC_CHECK_LOS_SEGMENT_REQUEST   1016
#define IDC_CHECK_LOS_VECTOR_REQUEST    1017
#define IDC_CHECK_IG_CONTROL            1018
#define IDC_CHECK_FRAME_START           1019
#define IDC_CHECK_CC_ENTITY_CONTROL     1020
#define IDC_CHECK_SHORT_COMPONENT_CONTROL 1021
#define IDC_CHECK_SHORT_ART_PART_CONTROL 1022
#define IDC_CHECK_CELESTIAL_SPHERE_CONTROL 1023
#define IDC_CHECK_ATMOSPHERE_CONTROL    1024
#define IDC_CHECK_MARITIME_COND_CONTROL 1025
#define IDC_CHECK_TERRESTRIAL_COND_CONTROL 1026
#define IDC_CHECK_WAVE_CONTROL          1027
#define IDC_CHECK_MOTION_TRACKER_CONTROL 1028
#define IDC_CHECK_ERM_DEFINITION        1029
#define IDC_CHECK_POSITION_REQUEST      1030
#define IDC_CHECK_ENV_CONDITIONS_REQ    1031

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
